### ISSUE TITLE
Reduce bundle size increase to zero :)

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#1]
By looking at the source code Feliz is using class with a constructor.

```fs
module Test

type IBorderStyle = interface end

type borderStyle() =
    static member inline dotted : IBorderStyle = unbox "dotted"
```

which generates:

```js
import { type } from "fable-library/Reflection.js";
import { declare } from "fable-library/Types.js";
export const borderStyle = declare(function Test_borderStyle() {});
export function borderStyle$reflection() {
  return type("Test.borderStyle");
}
export function borderStyle$$$$002Ector() {
  return this instanceof borderStyle ? borderStyle.call(this) : new borderStyle();
}
```

In order to minimize the bundle size, we can remove the constructor.

```fs
module Test

type IBorderStyle = interface end

type borderStyle =
    static member inline dotted : IBorderStyle = unbox "dotted"
```

this generates:

```js
import { type } from "fable-library/Reflection.js";
import { declare } from "fable-library/Types.js";
export const borderStyle = declare(function Test_borderStyle() {});
export function borderStyle$reflection() {
  return type("Test.borderStyle");
}
export const x = "dotted";
```

We can even go further and have no bundle size increase by using `Erase` attribute:

```fs
module Test

open Fable.Core

type IBorderStyle = interface end

[<Erase>]
type borderStyle =
    static member inline dotted : IBorderStyle = unbox "dotted"
```

generates ... nothing :stuck_out_tongue_winking_eye:  :tada:

**Comment by MangelMaxime** [comment]
Avoid `sprintf` for string concatenation because I remember that it's increasing the bundle size as `sprintf` includes a lot of modules/code. And if we are doing using it just for basic string concatenation it's not worth the drawback I think.

[Source](https://github.com/Zaid-Ajaj/Feliz/blob/master/src/BorderStyle.fs#L58)

I don't have any measurement for this one but could probably provide one if needed.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @MangelMaxime for checking this! I will look into it once the before the stable release :)

**Comment by Zaid-Ajaj** [comment]
Implemented!

**Comment by MangelMaxime** [comment]
There are still 3 types not converted yet:

- [TextDecorationStyle](https://github.com/Zaid-Ajaj/Feliz/blob/master/src/TextDecorationStyle.fs)
- [TextAlignment](https://github.com/Zaid-Ajaj/Feliz/blob/master/src/TextAlignment.fs)
- [TextDecorationStyle](https://github.com/Zaid-Ajaj/Feliz/blob/master/src/TextDecorationStyle.fs)

I list them here because I can't create a PR right now.

**Comment by Zaid-Ajaj** [comment]
I keep referencing the wrong issue in my commit messages :joy: but they are implemented and will be available in v0.9

**Comment by MangelMaxime** [comment]
Ah ok sorry, I was looking at master branch which got a new commit since them :)

**Comment by Zaid-Ajaj** [comment]
No I am sorry, I added the commit after reading your message, I meant that I referenced the wrong issue in my commit message 😅 never mind

**Comment by MangelMaxime** [comment]
About `sprintf` Elmish is already including it [source](https://github.com/elmish/elmish/blob/master/src/program.fs#L153) so it's up to you.

I know that we removed from Fulma for increase the bundle size.

Other than that, I don't have more tricks for size optimisation :)

**Comment by Zaid-Ajaj** [comment]
Made another issue for it to continue discussion from there :)
