### ISSUE TITLE
Rename prop.content to prop.children

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#10]
Is there a real value to use `prop.content` instead of `prop.children`?

**Comment by Zaid-Ajaj** [comment]
Children is plural so you expect a list of children whereas content expects a single child :)

**Comment by MangelMaxime** [comment]
Indeed, I am just worried about `content` being used by one of the HTML elements.

**Comment by MangelMaxime** [comment]
Actually it's the case: https://www.w3schools.com/tags/att_content.asp

**Comment by Zaid-Ajaj** [comment]
Yeah I checked that too, but it is only applied to `<meta>` tags in the  `<head>` section of the page so I don't that is react-specific

**Comment by MangelMaxime** [comment]
The problem is that people can't use Feliz to generates HTML (like a static website or templates) neither do SSR without an existing `index.html`

**Comment by Zaid-Ajaj** [comment]
Fixed 😛

**Comment by MangelMaxime** [comment]
Thank you ❤️ ❤️
