### ISSUE TITLE
Use FunctionComponent for ElmishComponent

### ISSUE THREAD

**Issue by marcpiechura** [Zaid-Ajaj/Feliz#101]
Hey,

currently it's not possible to use ElmishComponent with Hook based APIs, in my case makeStyles from MaterialUI, since you can use those only from within a FunctionComponent. 
So I've changed ElmishComponent to use FunctionComponent under the hood and it seems to work for me, here are the necessary changes

```
[<AutoOpen>]
module ElmishComponentExtensiosns =
    let private functionComponent p = 
        FunctionComponent.Of((fun (props) ->        
            let stateHook = Hooks.useState(fst props.Initial)

            let rec dispatch(msg: 'Msg) =                
                let (nextState, nextEffect) = props.Update msg stateHook.current
                stateHook.update nextState
                for subscriber in nextEffect do
                    subscriber(dispatch)

            let dispatchEffects () =                
                let initialEffect = snd props.Initial
                for subscriber in initialEffect do
                    subscriber(dispatch)

            Hooks.useEffect (dispatchEffects, [||])
                
            // if props changed reference, re-execute `init` from the program definition
            Hooks.useEffect (dispatchEffects, [|props|])

            props.Render stateHook.current dispatch
        ), memoizeWith = equalsButFunctions) p

    type React with
        /// Creates a standalone React component using an Elmish dispatch loop
        static member inline elmishComponent(name, init, update, render, ?key) =
            let fullKey =
                match key with
                | None -> name + string (Guid.NewGuid())
                | Some key -> name + "-" + key
            // Fable.React.Helpers.ofType<ElmishComponent<_, _>, _, _>
            functionComponent { Initial = init; Update = update; Render = render; key = fullKey }
                // [ ]

        /// Creates a standalone React component using an Elmish dispatch loop
        static member inline elmishComponent(name, init, update, render, ?key) =
            let fullKey =
                match key with
                | None -> name + string (Guid.NewGuid())
                | Some key -> name + "-" + key
            // Fable.React.Helpers.ofType<ElmishComponent<_, _>, _, _>
            functionComponent { Initial = init, Cmd.none; Update = update; Render = render; key = fullKey }
                // [ ]

        /// Creates a standalone React component using an Elmish dispatch loop
        static member inline elmishComponent(name, init, update, render, ?key) =
            let fullKey =
                match key with
                | None -> name + string (Guid.NewGuid())
                | Some key -> name + "-" + key
            // Fable.React.Helpers.ofType<ElmishComponent<_, _>, _, _>
            functionComponent
                { Initial = init, Cmd.none;
                  Update = fun msg state -> update msg state, Cmd.none;
                  Render = render
                  key = fullKey }
                // [ ]

        /// Creates a standalone React component using an Elmish dispatch loop
        static member inline elmishComponent(name, init, update, render, ?key) =
            let fullKey =
                match key with
                | None -> name + string (Guid.NewGuid())
                | Some key -> name + "-" + key
            // Fable.React.Helpers.ofType<ElmishComponent<_, _>, _, _>
            functionComponent
                { Initial = init;
                  Update = fun msg state -> update msg state, Cmd.none;
                  Render = render
                  key = fullKey }
                // [ ]
```

If that would work for you, I could send a PR or you can make the changes by yourself, what works best for you. Also one question, is there a reason to execute init and effects when the props reference changed?

**Comment by Zaid-Ajaj** [comment]
Hello @marcpiechura I am curious as to why this is the case: `currently it's not possible to use ElmishComponent with Hook based APIs, in my case makeStyles from MaterialUI, since you can use those only from within a FunctionComponent.` 

Don't you just need to write the following?
```fs
let app = React.functionComponent("App", fun () -> 
  let (flag, setFlat) = React.useState(true)
  React.elmishComponent(...)
```

About your implementation, I am pretty sure I tried that combination and didn't work because the order of hook usages matters and something went wrong while executing the subscribers in the loop inside `dispatch`. Does this implementation work properly for the counter example in the docs?

**Comment by marcpiechura** [comment]
> I am curious as to why this is the case:  

I've used it like this 
```
let private view' = 
   let styles = useStyles() // hook
   ....
   myHtmlView

let view = React.ElmishComponent ... view' 
```
and that doesn't work :) 
I haven't tried your workaround, but instead simply wrapped my `view'` inside a FunctionComponent  and used that for the ElmishCompoenent, which worked too, but I thought it would be better to use  FunctionComponent directly instead of having a FunctionComponent inside another Component...

But unfortunately you're right, my implementation doesn't work if you use `Cmd.batch`. It executes the dispatch function twice, but on the second execution the `stateHook.current` still contains the "old" state. So `IncrementTwice` will set the counter to 1, because update is called twice with message `Increment` and state `Count = 0` .... 

Since I don't know much about React or Hooks at all, I wasn't able to resolve this issue :( 

Regarding your suggestion, would a simple functionComponent at the top component work for all views, even child views or must it also be a functionComponent per view as the workaround I tried ?

**Comment by Zaid-Ajaj** [comment]
> Regarding your suggestion, would a simple functionComponent as the top component work for all views, even child views or must it also be a functionComponent per view as the workaround I tried ?

The guideline is simple: whenever you want to use hooks (i.e. `useStyles()` in this case) make sure to use them inside the definition of `React.functionComponent`. Then it doesn't matter how you use that function component. Docs are coming up soon!

> Since I don't know much about React or Hooks at all, I wasn't able to resolve this issue :(

I tried all kinds of implementations using hooks to make ElmishComponents but every time either some commands weren't executed or they were duplicated so it was a lot easier to go the Component route where stuff like that are simpler so I think I will keep it that way. Make sure to update `Feliz.ElmishComponents` to latest version, things got better now!

**Comment by marcpiechura** [comment]
Sounds good, thanks!
