### ISSUE TITLE
Proposal for the `type` attribute: omit it altogether

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#108]
Right now we have used the enum `withType` to specify the type of the Html `input` elements as follows:
```fs
Html.input [
  prop.className "form-control"
  prop.withType.password
  prop.valueOrDefault state.Whatever
]
```
The more I write it, the more weird it feels because `withType` is usually used the context of functions when chaining them using the `|>` operator but here they are just enums. 

In the recharts binding, I took the liberty to experiment with the `type` attribute because some components like `Line` and `Area` also have this property and I have chosen to omit it and use the value directly as a valid attribute for that chart in subject:
```fs
Recharts.area [
    area.monotone
    area.dataKey (fun point -> nameof point.uv)
    area.stroke "#8884d8"
    area.fillOpacity 1
    area.fill "url(#colorUv)"
]
```
Notice here the attribute `area.monotone` is actually short-hand for `type="monotone"` from the JS equivalent and I am happy with in, this is nice too for the native properties like that:
```fs
Html.input [
  prop.password
  prop.className "form-control"
  prop.valueOrDefault state.Whatever
]
``` 
Very short, you get used it quickly and doesn't feel weird. I would personally also like `props.types.password` but again that feels like too many key strokes...

I was wondering what you guys think of it: @MangelMaxime, @cmeeren, @zanaptak, @Shmew

**Comment by Shmew** [comment]
I definitely agree that `withType` feels awkward. I feel like not having `type'` or `withType` before the attribute name could be confusing to people though, it gives way to ambiguity. If it wasn't making bindings for an existing API I'd absolutely favor just doing `prop.password`. At the same time, intellisense solves a lot of these issues raised. 

In summary, I have no idea what's best. When I feel that way I usually just try to follow as closely to what the user would expect as possible, in this case it would probably be `type'`.

**Comment by MangelMaxime** [comment]
The problem from my point of view is that without prefix this makes `type` a special case and also "pollute" the "global" scope. Not having a prefix is also making it a bit harder for people to discover the different type possible while having the prefix user can just do `prop.<prefix>.` and see the list.

I have seen several people using `typ` abbreviation for `type` perhaps we could use it too. And to make it more discoverable we could add ` ``type`` ` with a doc comment mentionning `typ` abbreviate for people not liking double backtick.

**Comment by Zaid-Ajaj** [comment]
Alright, stupid idea then hahah, thanks guys for the feedback :smile:

**Comment by cmeeren** [comment]
The case seems closed, but for the record:

* I agree that `withType` is weird`
* I agree with @Shmew and @MangelMaxime that we should keep some kind of `type` prefix (better discovery, avoids namespace pollution and potential collision, etc.).
* I also agree with @Shmew that I'd rather see `type'`. It's searchable/discoverable, there's no ambiguity or confusion regarding whether the current `with` prefix means anything special, it's not uncommon to suffix names (especially reserved names) with apostrophe (or, as I mentioned in #13, with other stuff, e.g. Elm calls it `type_`), and, to turn @Zaid-Ajaj's argument back around, you get used to it very quickly. I simply do not buy the argument from #13 that an apostrophe suffix "always looks foreign and weird for F# beginners".

**Comment by zanaptak** [comment]
I would favor a better name while also keeping `type` in the name for intellisense/domain-representation purposes.

- `htmlType` (a la `htmlFor`)
- `typeName` (a la `className`)
- `typeValue`
- `typeAttribute`
- `typeText`, `typePassword`, etc.
- `textType`, `passwordType`, etc.
- ``` ``type`` ``` (Chicken and egg -- we say backticks are too unfamiliar, but maybe if we all used them more...?)

**Comment by Shmew** [comment]
Am I the only one that likes `type'`?

**Comment by cmeeren** [comment]
> * `` ``type`` `` (Chicken and egg -- we say backticks are too unfamiliar, but maybe if we all used them more...?)

IMHO the main problem with double backticks isn't related to familiarity; it's that they're fairly "noisy" (hence my suggestion for `type'`).
