### ISSUE TITLE
Export React component in npm

### ISSUE THREAD

**Issue by evilz** [Zaid-Ajaj/Feliz#110]
Hello,

I try to create component and use it in storyboard.

I try many setting in webpack.config but still not good. 
Have someone already done this ?

I use this in webpack
```json
 library:"mylib",
 libraryTarget: 'commonjs',
```

**Comment by Zaid-Ajaj** [comment]
Can you provide more context to this, for example how are you using storyboard? Maybe you have a project that I can take a look at?

**Comment by evilz** [comment]
Sorry it's storybook not storyboard ....

here the project as I have it actually : https://github.com/evilz/react-cirrus

**Comment by MangelMaxime** [comment]
@evilz I don't see where you are trying to export a react component in your `src` folder.

In theory, anything generated by `Feliz` is a react component/element.

```fs
let comp1 = Html.div [ ] [ ]

let comp2 name = Html.div [ ] [ prop.str name ] 
// Perhaps prop.str isn't valid for Feliz I never used it yet but you have the idea
```

For me, your question is more about how to export F# code for using it in a JavaScript project. (I say that because you are touching the webpack config)

Perhaps this answer can help https://stackoverflow.com/questions/53997440/how-to-expose-f-modules-public-functions-to-javascript-via-fable/54451390#54451390 ?

You can also use `exportDefault` in order to avoid having the `.api.` in your "path".

**Comment by evilz** [comment]
@MangelMaxime, yes that's it.

I tried this https://github.com/evilz/react-cirrus/blob/master/webpack.config.js#L68-L69

Do you mean I need to create a interface to expose as a default export ?

Something like this

```
type Cirrus =
    abstract Button : ButtonProps -> ReactElement

```

**Comment by MangelMaxime** [comment]
Creating an interface is not mandatory but it ensures that the generated names are not modified by Fable.

In general, if your `let` declaration is at the root level of the file it will not be modified. 

For example, [`basePage`](https://github.com/MangelMaxime/Nacara/blob/master/src/Layouts/Standard/Prelude.fs#L210) is at the root level of the file so I can do this in JavaScript: 

1. Import the module: https://github.com/thoth-org/Thoth.Elmish.FormBuilder/blob/master/nacara.js#L4
2. Use it: https://github.com/thoth-org/Thoth.Elmish.FormBuilder/blob/master/nacara.js#L40

Note that this example is using `fable-splitter` but the theory should stay the same with webpack.

Do you have an example of your declaration code and how you are trying to import it?

**Comment by evilz** [comment]
Thanks,

I try to change to this 
https://github.com/evilz/react-cirrus/blob/master/src/Main.fs#L13-L21

And use like that https://github.com/evilz/react-cirrus/blob/master/src/Main.fs#L13-L21

but the result is not good 
![image](https://user-images.githubusercontent.com/2937862/68711134-54427c80-0599-11ea-99e9-d4957bd40496.png)

**Comment by MangelMaxime** [comment]
Hum which object are you printing here?

```fs
module Thoth.RandomUser

open Fable.Core
open Fable.Core.JsInterop
open Fable.React

type Props =
    { test : string }

type ICirrus =
    abstract Button : Fable.React.FunctionComponent<Props>

let Circus = 
    { new ICirrus with
        member __.Button = FunctionComponent.Of(fun (props: Props) -> div [ ] [ ])
     
    }

// I think you are logging this object
JS.console.log Circus
// While you should log this one
JS.console.log Circus.Button
// And you can use it like that
JS.console.log (Circus.Button { test = "" })
```

See the console output in the REPL: [Live example](https://fable.io/repl/#?code=LYewJgrgNgpgBAFQBYgC5IHQCUCGA7MEYAVQGcYAnAKCpAAcY84AxHAI1gwGEQKZaGTVhxjdeogFKkAknlSV6Axi3acsMHAGNUNVAE8GcAAoV6pOAF4qcG3ADeceaVRwAXHGcUAlngDmcAF9dA3hpLi8KCghzK1s4dk8tFwAhCFRUECZ3YTUNbQxmCDxtL0yeYDpMxlQAHhMzAD4aWBdwik1oyzhrWwc8GAB3ODCIqPMBr3QeuJtgGGA2SjgAfWWMVPTMrsLi1FK8csr+uQwAeQAzAApzorhLulM6Und6p4BKOABaBrgwLwA3OAAbTgAF1gWC3tMbNCglQAPTw4aOJA+ADWcD0IAg8T4cCgIF8vh8-nQXnMIDYACsYNoqBIAMoYTSZUggTgE-xtDqkBFIgDqqNgmOxHhQ0DA+MJKPJcCq9KZLLwbI50u50XWaQyeD5cAAggQRTjNPg4NF4JN8V40fB0DgdIzmaz2aJOXd1aRNZsmA4nC4LHAAESBwJvIA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

You can also do

```fs
exportDefault
    { new ICirrus with
        member __.Button = FunctionComponent.Of(fun (props: Props) -> div [ ] [ ])
     
    }
```

If you want to import it as a default module and not name it `import default from '...'` VS `import { Button } from '....'` (syntax should be something similar that I never remember the correct one sorry ^^)

**Comment by evilz** [comment]
So it's maybe a bad configuration of webpack 🤔

**Comment by Zaid-Ajaj** [comment]
Hello @evilz is this issue resolved? Still need help? 

If it is resolved, please close the issue or let me know if you need help. Though I believe @MangelMaxime did a great job in his comment [above](https://github.com/Zaid-Ajaj/Feliz/issues/110#issuecomment-553300835)

**Comment by evilz** [comment]
Hi,

Let say it's ok since I did not try againfor a long time.
I will re-open if needed :)

It's now time to read your book 👍
