### ISSUE TITLE
Namespace misspelled

### ISSUE THREAD

**Issue by JordanMarr** [Zaid-Ajaj/Feliz#133]
I just happened to notice this typo while trying out Feliz yesterday for the first time:

open Feliz.ElmishComponents.ElmishComponentExtensio**sns**

Edit: I wasn't going to submit this as an issue until I saw your OSS talk from a few weeks ago where you specifically said to submit misspellings.

**Comment by cmeeren** [comment]
Nice catch! I'm not the maintainer here, but I'm sure @Zaid-Ajaj would appreciate a PR if you're able to do that :)

**Comment by Zaid-Ajaj** [comment]
A PR is more than welcome, really appreciate it!
