### ISSUE TITLE
Recursive React.functionComponent

### ISSUE THREAD

**Issue by JordanMarr** [Zaid-Ajaj/Feliz#137]
This is not necessarily a bug, but I wanted to at least mention a difference I found between Feliz `React.functionComponent` vs Fable `FunctionComponent.Of`.

Description:
When creating a recursive functionComponent, `React.functionComponent` shows an error when recursively calling itself with an implicit yield:

```
module CategoriesTree

open Feliz
open Fable.React

type Category = {
    Name: string
    SubCategories: Category list
}

let rec treeNode = React.functionComponent(fun (props: {| Category: Category |}) ->
    let isExpanded, setIsExpanded = React.useState(false)

    div [] [
        div [] [ str props.Category.Name ]
        if isExpanded then
            div [] [
                for c in props.Category.SubCategories do
                    //yield treeNode {| Category = c; |} // Explicit yield works
                    treeNode {| Category = c; |} // Implied yield fails
            ]
    ]
)

```

In comparison, `FunctionComponent.Of` allows both the implicit and explicit yield.

**Comment by JordanMarr** [comment]
It seems that ``FunctionComponent.Of`` always returns a ``FunctionComponent<'props>``, whereas ``functionComponent`` tries to return a ``'props -> unit`` in the error case.  
So maybe it's just a matter of locking down the ``functionComponent`` return type as ``FunctionComponent<'props>``?

**Comment by Zaid-Ajaj** [comment]
Hi @JordanMarr, I actually didn't know about the `yield` requirement for the components. I look into it and simplify it if possible, otherwise this goes to the documentation :smile:
