### ISSUE TITLE
Make classList and classes overloads of className

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#14]
AFAIK `className` is a space-separated string of class names to apply to the component/element. Why not make `classList` (and `classWhen`) and `classes` overloads of `className`? That would improve discoverability, remove confusing extra names for what is essentially the same property, and be more in line with the goal of this project as I understand it.

**Comment by cmeeren** [comment]
Also, it would remove a potential conflict with the `classes` prop that is used for more or less every Material-UI component.

**Comment by Zaid-Ajaj** [comment]
I liked the fact that classes is plural so that it takes a list of things, whereas `className` is supposed to take a single class(name). As for `classWhen`: the name implies the use of conditionals and will probably replace `classList` in the stable release. 

This is my rationale for the choices, I will keep this (and the other issues) open for suggestions until the stable release

**Comment by cmeeren** [comment]
Yep, I just figured that since you do overloads anyway for improved usability, then using different names for what is essentially the same thing (a list of classes) was confusing to end users. It's not self-documenting that there are multiple ways to add classes; you have to read the docs to get it. Whereas if everything that adds classes are just overloads of `className` (which AFAIK is the canonical React name), then all users immediately see the various overloads (ways to add classes) when looking at the Intellisense.

Happiness +1 :)

**Comment by Zaid-Ajaj** [comment]
For readability: use `classes`, `className` and `classWhen` 
For consistency & usability: use overloaded `classes` 
For conformity (with React): use overloaded `className` 

I am sure *there is* a way to strike a perfect balance but it is not an obvious choice to make here 

Also I really really appreciate your feedback, helps a lot to moving forward with this library :smile:

**Comment by cmeeren** [comment]
Yep, there are always tradeoffs... AFAIK the point of Feliz is discoverability/usability (it's certainly what brought me here), so I would definitely go with overloads in this case. I would be comfortable with overloaded `classes`, though IMHO it's better to follow established and google-able names, so I would go with `className`, which immediately indicates to users that it corresponds to the same React prop. Consistency, usability, and conformity. Yay!

Personally I don't find `classes`/`className`/`classWhen` more readable. `classWhen` in particular sounds very weird in my ears.

**Comment by cmeeren** [comment]
> Also I really really appreciate your feedback, helps a lot to moving forward with this library 😄

Happy to share my opinions! Note that they are in general [strong opinions, weakly held](https://blog.codinghorror.com/strong-opinions-weakly-held/). I can always change my mind in light of new realizations, information and compelling arguments. :)
