### ISSUE TITLE
Is their an equivalent to ofOption from Fable.React?

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#143]
In my projects, I often end up using [`ofOption`](https://github.com/fable-compiler/fable-react/blob/38c5d58d9fbcf39a597b714851e8e290b55fb5d2/src/Fable.React.Helpers.fs#L265) helper to make some part of the UI conditionally rendered because I can pass `Some xxx` or `None` easily as arguments between the functions.

For now, Feliz doesn't seem to have an equivalent implemented and so I am opening `Fable.React` only for accessing this helper.

**Comment by Zaid-Ajaj** [comment]
Hello Maxime, 

It is a good point to bring up and more generally the question is: "What helper functions should we bring over to Feliz from Fable.React?"

One of the things I really **disliked** about Fable.React is the *global* functions: `ofOption`, `ofInt`, `str` etc. Global functions coming from `[<AutoOpen>]` modules are hard to find if you don't read documentation. Besides the discoverability issue, I want to keep Feliz as simple as possible and not add unnecessary helpers for people who don't use them: the alternative approach is just as simple and everyone will understand what the following means:
```fs
match state.CurrentUser with 
| Some user -> renderUser user
| None -> Html.none
```
Here `Html.none` will be the main alternative as a return value.

Only after someone thinks that the above pattern is used too much and considered boilerplate, then  they can easily implement `ofOption` in their own apps once and make it `[<AutoOpen>]` :
```fs
[<AutoOpen>]
module Extensions 

open Feliz

let ofOption (element: Option<ReactElement>) : ReactElement = 
  match element with 
  | Some value -> value
  | None -> Html.none
```
Just like that. No need to add it to the main library if when it is not needed and when it is easy to add by the end users

**Comment by cmeeren** [comment]
I was thinking the same thing. 👍

**Comment by MangelMaxime** [comment]
I think the same about global helpers function and it's one of the strength of Feliz to help exploring using intellisense. 

I was asking because even if we can do `Html.` to get all the available "elements" I still missed `Html.none` so I was afraid to miss something else 😄 

Yes, I can add the helper to my different projects :)

**Comment by Zaid-Ajaj** [comment]
Hello @MangelMaxime I think this is considered resolved, right? I will close the issue. Please re-open if there is any further discussion

**Comment by MangelMaxime** [comment]
Yes, it is thank you for closing
