### ISSUE TITLE
Missing support for Html.Source and Video props

### ISSUE THREAD

**Issue by vrescobar** [Zaid-Ajaj/Feliz#149]
First of all, thank you for such awesome library, which in contrast to the default Elmish components is really friendly to use with the autocomplete; right now I am using it to create a personal blog and the experience has been great so far.

I see that most of the attributes for the video html tag are missing as well as the whole Source html element. Video and Source element specification:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video

Right now the easiest workaround seems to use `prop.dangerouslySetInnerHTML` with string templating as I do not see the way to set a custom made Html tag and set Html properties which are not a string key-pair.

``` F#
prop.dangerouslySetInnerHTML (sprintf """
<video poster="%s" loop autoplay muted >
      <source src="videos/IMG_5202.mp4" type="video/mp4">
</video>
""" backgroundPath)
```

My guess is that here could be the implementation together with the rest of the tags, but as I am still new to F# and I have never ever touched the react API before I am not that confident to make a PR to
`master/Feliz/Html.fs`

**Comment by Zaid-Ajaj** [comment]
Hello @vrescobar, thanks for the kind words. I am glad to hear that we are going in the right direction with this library :smile: 

As for missing elements and properties, I will try to add them as soon as possible.

**Comment by Shmew** [comment]
@vrescobar I put in a PR that just got merged that should fix this issue for you, feel free to re-open if you have any issues/suggestions!
