### ISSUE TITLE
missing <main> element

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#15]
I can't find `Html.main`. See `Fable.React.Standard.main`: https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React.Standard.fs#L57

Based on that list, there might be more missing, I haven't checked.

**Comment by Zaid-Ajaj** [comment]
I will add it soon :smile:

**Comment by phillipbaird** [comment]
The semantic element `header` appears to be missing as well.
