### ISSUE TITLE
Missing data values and Feliz Recharts

### ISSUE THREAD

**Issue by joahim** [Zaid-Ajaj/Feliz#151]
Is is possible to have missing values in Feliz Recharts similar to this Recharts example: http://recharts.org/en-US/examples/LineChartConnectNulls The `dataKey` functions in https://github.com/Zaid-Ajaj/Feliz/blob/master/Feliz.Recharts/Line.fs do not seem to support this. But maybe I'm missing something.

**Comment by Zaid-Ajaj** [comment]
Hello @joahim, it is certainly possible to add something like and allow `dataKey` to accept `float option`, `int option` or `string option`. This will account for the missing data points by returning `undefined` when the the value is `None` or the return the value itself when the datapoint is `Some value`. 

Would you like to give it a go and try to implement the optional values? I would really appreciate it :pray: adding an example to docs is a huge bonus 😍

**Comment by joahim** [comment]
Yes, I would be happy to give it a try.

**Comment by Zaid-Ajaj** [comment]
Fixed by #161
