### ISSUE TITLE
Make onCheckedChange and onTextChange overloads of onChanged

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#16]
Kinda similar to #14 (very happy you did that, thanks!).

I propose that `onCheckedChange` and `onTextChange` become overloads of `onChanged`. As a developer, I instinctively reach for `onChanged` when I want that behavior, because it's a well-known concept. I can then happily discover that it has simplified convenience overloads for inputs and checkboxes. Contrast this to the current names, which I'd have to discover and read about separately. Consolidating them under a well-known (and semantically correct) name improves discoverability, reduces mental load (less terms to remember) and IMHO also improves readability in this case (which variant is used isn't important enough to warrant separate names; they all do the same general thing and the compiler will complain if something's wrong.)

(Also, the current names should probably both end with `d`.)

**Comment by Zaid-Ajaj** [comment]
Sounds good to me but I think we should keep  `onChange` instead of `onChanged` because that is the name of the react/html attribute

**Comment by cmeeren** [comment]
Of course! My bad, I misread the name in the code (I thought the existing name for `onChange` was `onChanged` and figured that was the correct one.)

**Comment by Zaid-Ajaj** [comment]
Added the overloads, but I've kept `onTextChange` for emotional attachment reasons :P it will probably be filtered out in the stable release
