### ISSUE TITLE
Invalid DOM property `tabindex`. Did you mean `tabIndex`?

### ISSUE THREAD

**Issue by pbryon** [Zaid-Ajaj/Feliz#160]
This is caused by [Properties.fs](https://github.com/Zaid-Ajaj/Feliz/blob/master/Feliz/Properties.fs) on line `1091` (right-hand side).

I would have preferred to submit a PR, but I've never done that on GitHub and couldn't find instructions on the [Contributing page](https://zaid-ajaj.github.io/Feliz/#/Feliz/Contributing).

**Comment by Zaid-Ajaj** [comment]
Hi there @pbryon, thanks a lot for reporting the issue! I have published a new version as of 0.74.1 and should be available soon from nuget

**Comment by pbryon** [comment]
@Zaid-Ajaj That was incredibly fast, thanks a lot!
