### ISSUE TITLE
Feliz needs an update to be compatible with Fable.React

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#164]
Fable.React 6.0.0 removed the `type FunctionComponent<'Props> = 'Props -> ReactElement`.

Feliz is using it internally [here](https://github.com/Zaid-Ajaj/Feliz/blob/master/Feliz/React.fs#L39). Perhaps there are other places.

Reported by @OnurGumus on Gitter with this reproduction step

> @MangelMaxime  basically 
> 1- )create a Fable.Elmish.React app
> 2-) Update to latest version of packages
> 3-) Add Feliz
> 4-) Change your view to
> ```
> open Feliz
> let root model dispatch =
>     Html.div [
>         prop.custom("onur",1)
>     ]
> ```

**Comment by Zaid-Ajaj** [comment]
Fixed in #165
