### ISSUE TITLE
Dispatch from Component back to parent?

### ISSUE THREAD

**Issue by juselius** [Zaid-Ajaj/Feliz#167]
Using `React.functionComponent`, how can I update the "parent" model? 

I have tried the following approach, but the dispatch back to the callee doesn't come trough from some reason.

```fsharp
module MyAction

type Model = bool

let update model _ = model 

let actionButton = 
  React.functionComponent(fun (onAction : Model -> unit) ->
    let model, dispatch = React.useReducer (update, false)
    Html.button [ 
        prop.text "Action!"
        prop.onClick (fun _ -> onAction true) 
    ]
  )
```

Usage:
```fsharp
actionButton (SomeAction >> dispatch)
```
I have used this approach extensively without problems with  `Fable.Reaction`, and I don't really see the difference.

**Comment by MangelMaxime** [comment]
Hello, 

react components only accept POJO( Records in F# world) as arguments so you need to write something like that:

````fs
type ActionButtonProps =
    {
        OnAction : Model -> unit
    }

let actionButton = 
  React.functionComponent(fun (props : ActionButtonProps) ->
    let model, dispatch = React.useReducer (update, false)
    Html.button [ 
        prop.text "Action!"
        prop.onClick (fun _ -> props.OnAction true) 
    ]
  )
```

See this page for more informations and examples: https://zaid-ajaj.github.io/Feliz/#/Feliz/React/CommonPitfalls

You can also use anonymous record if you prefer not to define a complete type.

**Comment by juselius** [comment]
Ahh, stupid me! Thank you! It's actually what I'm doing in Reaction as well. I just wanted to be terse since I only had one option...

**Comment by Shmew** [comment]
I'll also add in you can pass the callback to a child in the same method as above, you'll want to make sure you wrap it in `React.useCallback`.

**Comment by juselius** [comment]
Good point @Shmew!

**Comment by Zaid-Ajaj** [comment]
Hi @juselius I believe this issue is resolved so I will close it for now, please re-open if you counter such issues again or if you have any question :smile:

**Comment by juselius** [comment]
Keep closed @Zaid-Ajaj! 

A few comments though. I recently switched from Fable.React to Feliz, and I'm very happy and impressed! I also think the tight and natural integration with Bulma is brilliant, and Feliz.Router nicely gets rid of all sorts of ugly hacks. Keep up the good work!

But there is always a but. Having programmed primarily in F# and Haskell for the past 7-8 years, I have long since gotten used to that if code compiles, it works. But here we are, and I think this issue is a blemish. I don't immediately see a (practical) solution to the problem, but it annoys me that I so easily can write legal F#, which does not work. And worse, doesn't even give me an error at runtime.

**Comment by Zaid-Ajaj** [comment]
> A few comments though. I recently switched from Fable.React to Feliz, and I'm very happy and impressed! I also think the tight and natural integration with Bulma is brilliant, and Feliz.Router nicely gets rid of all sorts of ugly hacks. Keep up the good work!

@juselius Thank you for the kind words, I am glad to hear you are enjoying Feliz :100:

> Having programmed primarily in F# and Haskell for the past 7-8 years, I have long since gotten used to that if code compiles, it works. But here we are, and I think this issue is a blemish. I don't immediately see a (practical) solution to the problem, but it annoys me that I so easily can write legal F#, which does not work. And worse, doesn't even give me an error at runtime.

I have thought about this before and almost every runtime "solution" has tradeoffs from using Reflection and increasing the generated bundle size. 

My ideal solution would be to have a specialized F# analyzer for Feliz (something like [this one](https://github.com/Zaid-Ajaj/Npgsql.FSharp.Analyzer) which detects these definitions and suggests fixes while writing the code along with other nice warning when standard HTML attributes are incorrectly used (for example using `prop.children` inside `Html.input`). Unfortunately I can't give you a timeframe in which I will start working on it mainly to lack of time but also to some technical issues in developing F# analyzers themselves

**Comment by juselius** [comment]
Hmm, I wonder if this is something Fable could support as part of the interop system? An annotation that a function only accepts POJO for particular arguments? 

Another thing which would be cool, would be the `implicit yield` equivalent of `prop.children`. Prop.children often causes similar indentation behavior as with Fable.React, and getting rid of it would make the code more readable. Just a thought.

**Comment by Shmew** [comment]
The way to solve the runtime issues is to provide interfaces to define what is allowed for each element, similar to what I've done in `Feliz.Plotly`. The issue here is that every single attribute would need its own interface, that would then inherit from each element type. Definitely not fun to implement.

**Comment by Zaid-Ajaj** [comment]
> Hmm, I wonder if this is something Fable could support as part of the interop system? An annotation that a function only accepts POJO for particular arguments?

Fable had that before but it was removed because AFAIK it caused for many differences between how normal F# behaved vs. Fable especially when it came to reflection. 

> Another thing which would be cool, would be the implicit yield equivalent of prop.children. Prop.children often causes similar indentation behavior as with Fable.React, and getting rid of it would make the code more readable. Just a thought.

I am open to suggestions, the current approach is made so that we don't do any unnecessary extra runtime operations more than we already do to make the properties align with what React expects and because we want to ensure compatibility between Feliz and Fable.React because if we mix attributes and children in the same list we would need to come with a shared type for both and having to split the props into attributes + children during runtime.

**Comment by Shmew** [comment]
The implicit stuff with `prop.children` also becomes possible with this system, where the allowed interface accepts both the properties and children of that type, and then you'd have to partition the list and create the `prop.children` call. Not sure if that would have run-time impact or not.

**Comment by Zaid-Ajaj** [comment]
> you'd have to partition the list and create the prop.children call.

That is exactly what I am trying to avoid and the reason that I dismissed this approach early on when designing Feliz.

**Comment by juselius** [comment]
@Shmew I guess it should be possible to generate all those interfaces from a XSD or DTD. I started something similar a few years ago in the context of BIML, but never got around to actually complete the project. 

Somewhere in the back of my head I have an itch that rank-2 polymorphism might be a solution (https://www.gresearch.co.uk/article/squeezing-more-out-of-the-f-type-system-introducing-crates), but I don't know exactly how yet. When I get my head back overt the surface, I'll think more about it.

**Comment by zelenij** [comment]
@Zaid-Ajaj do you think it's possible to have an example on how to update (lift?) state change from child to parent in Feliz/Fable please? I can't figure it for the life of me, which limited knowledge of React doesn't help, of course.
