### ISSUE TITLE
Missing property for Html.meta 'http-equiv'

### ISSUE THREAD

**Issue by bengobeil** [Zaid-Ajaj/Feliz#171]
Hi,

I can't seem to find it in the source code. Am I missing something?

I can add it if it is.

Thanks,
Ben

**Comment by Shmew** [comment]
Hey @bengobeil,

Nope, you're not missing anything!

I went ahead and made the [changes](https://github.com/Zaid-Ajaj/Feliz/pull/172) while I was in the file.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @Shmew for the PR, it has now been added as of v0.79.0 which should available soon on nuget :rocket:

**Comment by bengobeil** [comment]
Awesome, thanks!
