### ISSUE TITLE
Component name showing up as Anonymous

### ISSUE THREAD

**Issue by kerams** [Zaid-Ajaj/Feliz#181]
I've just updated to Fable.React v6 and am using `Feliz.React.memo (name * areEqual * render)` to create a component. When I check the components in the browser, the name is not propagated. Currently I am unable to use `FunctionComponent.Of`, so I'm not sure if this is a problem in Feliz or in the new version of Fable.React.

Edit: the names are there when I switch to `Feliz.React.functionComponent`

**Comment by kerams** [comment]
This could be a problem in React dev tools https://github.com/facebook/react/issues/18026

**Comment by Shmew** [comment]
Looks like it is related to dev-tools then. 

Are you on the current version? 

Does downgrading resolve it?

**Comment by kerams** [comment]
Changing `memoElementType?displayName` to `renderElement?displayName` here does:
https://github.com/Zaid-Ajaj/Feliz/blob/2a0b9341c1e1c429bf483e4ddac05c002ff3c34c/Feliz/React.fs#L43-L44
