### ISSUE TITLE
Template Tests project TargetFramework set to netcoreapp3.0

### ISSUE THREAD

**Issue by esuxnw** [Zaid-Ajaj/Feliz#198]
This prevents the project from restoring and building.

<TargetFramework>netcoreapp3.0</TargetFramework>

**Comment by Zaid-Ajaj** [comment]
Hi @esuxnw, thanks a lot for filing the issue 🙏 I have published a new version of the template which aligns the version of test project to netcoreapp3.1 Please update the template as described in [the docs](https://zaid-ajaj.github.io/Feliz/#/Feliz/ProjectTemplate) and recreate the project :smile:
