### ISSUE TITLE
State is not reset for useElmish hooks

### ISSUE THREAD

**Issue by albertwoo** [Zaid-Ajaj/Feliz#199]
The new useElmish hooks accept a dependencies, I think if the dependencies changes we should set the state to initState and try to dispatch the initCmd.
I think we should add code in the position:

https://github.com/Zaid-Ajaj/Feliz/blob/aa0a742237fd8329cb942f192dfa48200e2f81c4/Feliz.UseElmish/UseElmish.fs#L90-L92

And modify like:
```fsharp
            React.useEffect((fun () ->
                state.current <- fst init
                setChildState()

                snd init
                |> List.iter (fun sub -> sub dispatch)), dependencies)
```

**Comment by Zaid-Ajaj** [comment]
Hello @albertwoo, thanks a lot for filing and for the fix, this is indeed better to reset everything, not just re-issuing the initial commands 💯 

I have just released a new version v1.2.1 which includes the fix 🚀 can you take it for a spin? 

Please reopen the issue if the problem persists
