### ISSUE TITLE
Add useState overload

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Feliz#200]
The setter function for `React.useState` supports the updater syntax of `currentValue -> newValue -> unit`, currently we only support `newValue -> unit`.

**Comment by Shmew** [comment]
Turns out this is only really around to cover some certain use cases that don't really exist with Fable. Closing this for now, if someone provides a convincing need for it we can revisit.

**Comment by Zaid-Ajaj** [comment]
Actually hitting an edge case which this overload of `useState` solve when updating arrays. Closures cache the data used from the state values that are created on the initial render. This overload avoids using cached data in closures and instead tabs into the data from cached in React state tree. 

See related issue in [React#React Hooks useState updating an array](https://github.com/facebook/react/issues/15041)

**Comment by Zaid-Ajaj** [comment]
Workaround
```fs
type React with 
    static member useStateWithUpdater (initial: 't) : ('t * (('t -> 't) -> unit)) = import "useState" "react"
```

**Comment by Shmew** [comment]
LGTM

**Comment by Zaid-Ajaj** [comment]
Added as of v1.14 :rocket:
