### ISSUE TITLE
Investigate adding Fast-Refresh plugin into the Feliz.Template

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#203]
In order to migrate the template gradually into a standalone React app instead of Elmish and only use Elmish when needed via Feliz.UseElmish library

**Comment by Zaid-Ajaj** [comment]
OK so my attempts aren't yielding much results :disappointed: if someone gives this a try and succeeds, please let us know :pray:

**Comment by aspnetde** [comment]
If I wanted to look into it, where would I have to start?

**Comment by Shmew** [comment]
[Here's an app using fast-refresh](https://github.com/Shmew/Feliz.Recoil/tree/master/docs), [webpack.config.js](https://github.com/Shmew/Feliz.Recoil/blob/master/webpack.config.js), [package.json](https://github.com/Shmew/Feliz.Recoil/blob/master/package.json), hopefully that should help give you an idea. It's pretty straightforward for the most part.

**Comment by Zaid-Ajaj** [comment]
Follow up discussion on this issue from the fast-refresh plugin repository in [Fable support for Feliz/React applications](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/150)

**Comment by Zaid-Ajaj** [comment]
Almost done, waiting on two issues: 
 - [Exporting an alias to a CSS module breaks react-refresh and causes full page refresh](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/260) for scoped stylesheet modules unless they are marked `private` 
 - [Using extended classes for props doesn't get picked up by react-refresh](https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/258) because records as props use extended classes (for now using anon records or multiple parameters works better for authoring React components in Fable 3)

**Comment by Jmaharman** [comment]
Isn’t the issue with both of these problems that you can only export React components from a file if fast refresh is going to work? I.e you cannot export anything else, otherwise it cannot create the boundary and goes up the tree?

**Comment by Zaid-Ajaj** [comment]
Current template supports react-refresh just fine 😄
