### ISSUE TITLE
Subscribing to JS events with UseElmish

### ISSUE THREAD

**Issue by kaashyapan** [Zaid-Ajaj/Feliz#206]
I'm porting an Elm app to Feliz with useElmish.
There is some JS code that uses 'ports' to trigger subscriptions upon the occurrence of some events in the js world. I am not sure how to port this.

The js callback has to call a fable function which triggers a Msg in elmish.
1) If I use a pure js to fable call, I dont have the dispatch. (Unless there is a way to reach into the compiled fable code and call a function from js)
2) I tried React.useEffects,  (I dont know React well enough.) in which case I dont know how to call the fable function that exists inside React.functionComponent anonymous function.

Any advice ?

**Comment by kaashyapan** [comment]
Thanks for your help. But I'm still a bit challenged by this.

I'm trying to upload a file using [Evaporate.js](https://github.com/TTLabs/EvaporateJS) library. The Evaporate.add js method call takes callback functions for started & progress events. I want to translate these js events into Elmish messages.

I've read through this [create js object with a function inside](https://github.com/fable-compiler/Fable/issues/1381) and this [..produce a command](https://github.com/elmish/elmish/issues/150) which described the subscriber approach.

My efforts so far have been as follows

I used ts2fable to produce [Evaporate.fs](https://gist.github.com/kaashyapan/df4948dda82987f7508f8fb4427d2439)

Because the Cmd.OfSub produces a Cmd<Msg>, I changed from 
`abstract started: (string -> unit) option with get, set`
to
`abstract started: (string -> 'a) option with get, set`


My Messages
```
    | UploadTransferPcnt of float
    | UploadError
    | UploadComplete
    | UploadStarted

```
My Sub
```
module Sub =
    let receivedCallbackMsg msg dispatch = dispatch msg
```


My update function
```

            let addConfig = createEmpty<Evaporate.AddConfig>
            addConfig.name <- file.name
            addConfig.file <- file
            addConfig.started <-
                Some(fun str ->
                    Cmd.ofSub (Sub.receivedCallbackMsg UploadStarted)
                    )
            addConfig.progress <-
                Some(fun pcnt _ ->
                    Cmd.ofSub (Sub.receivedCallbackMsg (UploadTransferPcnt pcnt))
                    )

            let ev = state.ev.Value       // I put the evaporate js object in my state for now
            { state with
                  WorkflowState' = Uploading },
            Cmd.OfPromise.either ev.add addConfig PromiseSuccess PromiseError
```
The above code uploads a file and returns the PromiseSuccess but the Cmd.ofSub messages are lost.

How does one get the messages produced by Cmd.ofSub inside the callback functions passed to JS back into the event loop ?

**Comment by Shmew** [comment]
There are two ways you can accomplish this.

Firstly you need to create a function that given a dispatch creates the object and returns unit. So the signature is `'Msg -> unit`. Inside of that function you will register that passed in dispatch function with the `started`, `paused`, etc. 

Once you have this, in your component you can call the function with the dispatch, or inside your update (or in your init) do a `Cmd.sub` so you can pass in the dispatch to that function. 

In either of those cases when the object has an update to dispatch it will be sent to your model.

**Comment by kaashyapan** [comment]
Cody, many thanks for your time and advice. 
I was able to accomplish what I wanted.

I'll leave a few code snippets here for posterity.
These are the callback messages
```
type UploadMessages =
    | TransferPcnt of float
    | Error of string
    | Complete of string
    | Start of string
    | Initiate
```
One Msg to hold the callback messages
```
type Msg =
    | EvaporateCallBack of UploadMessages
```
The function that takes in params and dispatch and constructs the js object with the necessary callback functions passing an Elmish Msg to dispatch
```
let callJsUpload (fileParams: FileParams) (dispatch: Msg -> unit) =
    let addConfig =
        createObj
            [ "started"
              ==> (fun str ->
                  let uploadMsg = Start str
                  (EvaporateCallBack uploadMsg) |> dispatch)

              "progress"
              ==> (fun pcnt _ ->
                  let uploadMsg = TransferPcnt pcnt
                  (EvaporateCallBack uploadMsg) |> dispatch)

              "complete"
              ==> (fun _ str _ ->
                  let uploadMsg = Complete str
                  (EvaporateCallBack uploadMsg) |> dispatch) ]

    jsUploadAdd addConfig
```

The sub that passes the dispatch to the function that invokes the JS function
```
module Sub =
    let startUpload (fileParams: FileParams) (msg: Msg) (dispatch: Msg -> unit) =
        callJsUpload fileParams dispatch
        dispatch msg
```

In the update function call the Cmd.ofSub and also handle the Callback msgs
```
            Cmd.ofSub (Sub.startUpload fileObj (EvaporateCallBack Initiate))
```
```
    | EvaporateCallBack (msg': UploadMessages) ->
        match msg' with
        | TransferPcnt f ->
                { state with
                      UploadState = Progress("", f) },
                Cmd.none
        | Start str -> { state with UploadState = Started str }, Cmd.none
        | Error str -> { state with UploadState = Errored str }, Cmd.none
        | Complete str ->
            { state with
                  UploadState = Completed str },
            Cmd.none
        | Initiate -> state, Cmd.none

```
