### ISSUE TITLE
Possible bug with useMemo

### ISSUE THREAD

**Issue by FranciscoMontanez** [Zaid-Ajaj/Feliz#211]
Hello, I'm attempting to re-compute a memoized value based on a prop change but it doesn't seem to work.

```
let myFunComp = React.functionComponent("myfuncomp", fun (props: {| lst:Item list; state:State; dispatch:Msg->unit; selectedItem:Item option |}) ->
  let items, setItems = React.useState(lst)
  let onSelectionChanged selected = selected |> UpdateSelectedItem |> props.dispatch
  let canSelectItem = 
    fun _ _ ->
      match props.state with
      | Selecting -> true
      | _ -> false
  let getKey = fun (item:Item) -> item.Id.ToString()

  let selection, deps = React.useMemo(fun () -> SingleSelectionHelper(canSelectItem = canSelectItem, getKey = getKey, onSelectionChanged = onSelectionChanged, items = items), [| box props.state |])

  Html.div [
    prop.custom("data-is-scrollable", true)
    prop.children [
      Fabric.detailsList [
        detailsList.setKey "set"
        detailsList.items items
        detailsList.selection selection
      ]
    ]
  ])


let myFunCompMemo = React.memo(render = myFunComp, areEqual = Fable.React.Helpers.equalsButFunctions)

```

Expected:

When **props.state** changes to *Selecting* , `canSelectItem` in *selection*  = **true**
When **props.state** changes to any other state, `canSelectItem` in *selection*  = **false**

Actual:

*selection* is not re-computed when **props.state** changes. `canSelectItem` in *selection* is  kept at its initial value:

( if *Selecting* was the initial state then `canSelectItem` will stay as **true** )

**Comment by Shmew** [comment]
Hi @FranciscoMontanez, you need to pass a dependency array if you don't want that value to be static. 

@Zaid-Ajaj I made `useMemo` default to an empty array if nothing was passed in, as having a value wrapped in `useMemo` doesn't actually do anything when not given a dep array, but seeing this issue I wonder if we should change it to just always re-render the value when no array is passed in?

**Comment by FranciscoMontanez** [comment]
Hi @Shmew, thanks for the help! It turns out I was missing parens around my create function. Without them, my create function and dependency array were being tupled up as the first argument for `useMemo`. Wrapping the create function makes it less confusing, I think. This does not solve my issue, but it leads me to believe that the problem lies elsewhere and not with `useMemo`.
```
let createSelection() = SingleSelectionHelper(canSelectItem = canSelectItem, getKey = getKey, onSelectionChanged = onSelectionChanged, items = items)
let selection = React.useMemo(createSelection, [| box props.state |])
```
