### ISSUE TITLE
Escape hatch for missing properties

### ISSUE THREAD

**Issue by UnoSD** [Zaid-Ajaj/Feliz#219]
Hi, thank you for your library.

I'm using `Feliz.Recharts`,

is there any escape hatch in case of missing props and I am being blind? if not, can you please add this feature to fallback when you can't use idiomatic Feliz API?

Otherwise, when finding this issues, consumers would be forced to fall back to `Fable.Recharts`.

In my particular case, I need the react to the `pieChart` event `activeShape`. But would be useful to have a generic fallback in case other elements are missing.

EDIT: I realised I only searched for a `prop.custom`, maybe there is something to convert an `IProps` to `IReactProperty`? I'm not sure what to look up in the code/assembly to find it.

Thanks

**Comment by Shmew** [comment]
You can use `Interop.mkAttr "activeShape" someValue`, but more ideal would be a PR 😉

**Comment by UnoSD** [comment]
@Shmew sure, I can give it a go. I had to ask first as I would have attempted to implement the fallback mechanism if it wasn't there instead of the specific event.

**Comment by Shmew** [comment]
> Btw, is there anything in the repo to convert an IProp to an IReactProperty?

You might be able to unbox it, I'm not really sure.
