### ISSUE TITLE
Consolidate and expand children prop

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#22]
AFAIK React's `children` prop accepts a "node", which can be a string, number, component, or an array of any of these. (A `list` of these also seems to work, based on cursory experimentation.)

I therefore suggest the following:

* Rename `prop.text` and `prop.innerText` to `prop.children`, by the same reasoning as in #14/#15
* Add a `string seq` overload to `children`, which can be useful as an effective concatenation technique, as far as I've understood the React reconciliation mechanism. (Strictly speaking you could add `int seq`, `float seq` etc. but I'm unsure how useful they are, so perhaps don't add them before someone actually needs them)

**Comment by zanaptak** [comment]
I disagree with issues 22-25. `text`/`innerText` is a shortcut helper specifically for inserting text, not a general "insert a child node" helper. The internal API of the React children prop does not apply, this is about the Feliz consumer API an an adapter layer in this case. So distinguishing it from `prop.children` in some way seems appropriate, as does performing the standard `string` conversion on the parameter given the `text` intent of the helper.

**Comment by cmeeren** [comment]
> Regarding the first bullet point and by extension #23/#24/#25, `text`/`innerText` is a shortcut helper specifically for inserting text, not a general "insert a child node" helper.

Strings are valid React children, though.

> The internal API of the React children prop does not apply, this is about the Feliz consumer API as an adapter layer in this case.

I don't understand, could you elaborate? It looks to me like Feliz generates a `children` prop.

> and by extension #23/#24/#25

I read over them again to be sure, but as far as I can tell, they are orthogonal to this issue.

**Comment by Zaid-Ajaj** [comment]
@cmeeren 

I don't think it is *always* good to strictly replicate the React API, in this case I chose for `text` instead of children because I find it making more sense and easier to think about when you look for things: 
 - "I need to change the text of the button => I will try to find a property that has the word 'text' in it" 😍  
 - "I have to set the children of an element where it will have one child of type text because React children also takes a string and happens to be compatible"  😒 

> even though the documentation indicates otherwise

How is that so? The docs are saying that this is just a shortcut for `children [ Html.text value ]` which ultimately results in the element having the content provided

**Comment by cmeeren** [comment]
Fair point :)

Re. the docs: You're right, the end result is the same.

I still suggest adding a `string seq` overload to `prop.text`, then, since AFAIK it may cause less re-renders than concatenating a string yourself and rendering that as a single node.

**Comment by Zaid-Ajaj** [comment]
> I still suggest adding a `string seq` overload to `prop.text`, then, since AFAIK it may cause less re-renders than concatenating a string yourself and rendering that as a single node.

I don't it makes a lot of sense for prop.text to accept `string seq`. if you are reading through the overloads of `prop.text` and you see string seq, what would you think? Again in React primitives but who actually uses that and isn't that just a convenience helper to make JSX work properly? I would rather wait for a good use-case with examples to re-open the issue and implement it than trying to mimic the React API 1-to-1

**Comment by Zaid-Ajaj** [comment]
> it may cause less re-renders

It won't cause less re-renders, it will save you the computation of concatenation (which React will do anyways)

**Comment by cmeeren** [comment]
IIRC the reason it will save re-renders is because React will re-use the already rendered nodes for unchanged strings. Can't remember where I picked that up, it's a long time ago... So I might misremember. Is it incorrecft?

**Comment by Zaid-Ajaj** [comment]
I don't know for sure to be honest but I don't think it really matters considering how uncommon this construct is used (in my experience)
