### ISSUE TITLE
Conditional className

### ISSUE THREAD

**Issue by christoph-feb22** [Zaid-Ajaj/Feliz#226]
Hi there,

after updating to a current release I realized, that the property overload for conditional class names was removed. Is there any replacement for that overload or any reason why it was removed?

**Comment by Zaid-Ajaj** [comment]
Hi @christoph-feb22, the conditional overload is removed because it is unnecessary since latest F# supports implicit yield which means that this snippet:
```fs
prop.className [ 
  true, "primary"; 
  state.IsLoading, "is-loading" 
]
```
can be re-written as 
```fs
prop.className [
  "primary"
  if state.IsLoading then "is-loading"
]
```
Please let us know if you have trouble using this pattern.

**Comment by christoph-feb22** [comment]
Hi @Zaid-Ajaj,
thank you for your fast response.
I didnt thought about using the implicit yields there. Thank you!
