### ISSUE TITLE
Support for slot and part html attribute

### ISSUE THREAD

**Issue by OnurGumus** [Zaid-Ajaj/Feliz#231]
There is a slot attribute used for web components. So it's a good idea to implement it. Currently, I use

```
 prop.custom("slot", "myslot")
```

there is also `part` attribute.

**Comment by Zaid-Ajaj** [comment]
Added prop.slot in Feliz v1.8

**Comment by OnurGumus** [comment]
what about part?

**Comment by Zaid-Ajaj** [comment]
I missed that one. Now added is part (no pun intended) of Feliz v1.9 :wink:
