### ISSUE TITLE
Docs for the router do not work

### ISSUE THREAD

**Issue by 0x53A** [Zaid-Ajaj/Feliz#232]
![image](https://user-images.githubusercontent.com/4236651/88208237-37deff80-cc51-11ea-8f1c-68c4323526e7.png)

**Comment by Zaid-Ajaj** [comment]
Hmm that looks weird, maybe you have a cache issue? Because it looks like it is working fine:

![2020-07-22 20_41_13-Feliz](https://user-images.githubusercontent.com/13316248/88215345-cb1d3280-cc5b-11ea-95e4-eb4860f151f3.png)

**Comment by Shmew** [comment]
I cleared my cache and loaded the docs and I can see it fine as well.

**Comment by 0x53A** [comment]
Yeah, sorry, my work firewall is broken ...
