### ISSUE TITLE
Custom web element useState problem

### ISSUE THREAD

**Issue by OnurGumus** [Zaid-Ajaj/Feliz#233]
I have a very strange problem, when I use feliz in a custom web component within shadowroot, Feliz' React.useState doesn't work as I expected. Here's a comparative case
```
module Foo

open Feliz
open Fable.React

let feliz =
    React.functionComponent
        ((fun (props: {| initCount: int |}) ->
            let (s, update) = React.useState props.initCount
            Html.button
                [ prop.text ("Times clicked: " + s.ToString())
                  prop.onClick (fun _ -> update (s + 1)) ]))

let fable =
    React.functionComponent (fun (props: {| initCount: int |}) ->
        let state = Hooks.useState (props.initCount)
        Html.button
            [ prop.text ("Times clicked: " + state.current.ToString())
              prop.onClick (fun _ -> state.update (fun state -> state + 1)) ])

```

I have the same component as above. However, in one I use Feliz for state hook and on the other I use fable hook
Then the use case is

```
    member this.render() =
        let items =            
            React.fragment [
                    Foo.fable {|initCount = 0|}
                    Foo.feliz {|initCount = 0|}
            ]
        ReactDOM.render(items, container.Value) 
) 
```

Basically I have some custom web component
Then the fable version works expectedly where as feliz one stuck on 1.  The onclick triggers fine, but somehow state doesn't change.  What am I missing?

**Comment by Zaid-Ajaj** [comment]
Hi @OnurGumus, can you please provide a small repo where the problem occurs so that we can debug it too? The used components look exactly the same to me so I can't tell right away where the problem is

**Comment by OnurGumus** [comment]
Hi , in a different project the above code work. Since I can't isolate the issue , I will close it for now. I will re open if I manage to isolate it.
