### ISSUE TITLE
Validity of Html.text list overload?

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#238]
`Html.text` has an overload taking a list parameter and creating a `<text>` element.

https://github.com/Zaid-Ajaj/Feliz/blob/a0e39f6cf2fa411f25bea524b6db05d8d3a2edfe/Feliz/Html.fs#L709

Should this overload exist?

As far as I can tell, `<text>` is not a valid HTML element ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element), [Spec](https://www.w3.org/TR/html52/), [Validator](https://validator.w3.org/)).

I imagine it works by accident in practice due to browser leniency treating it as a div.

I'm wondering if Html.text should only allow scalar values and serve strictly as a shortcut for bare text, rather than a non-standard element. And users wanting to add props or children would have to explicitly change it to div/span or something.

**Comment by Zaid-Ajaj** [comment]
I believe this overload is for [SVG text](https://www.w3schools.com/graphics/svg_text.asp) not just HTML
