### ISSUE TITLE
Remove bool overload of text/innerText(/children)

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#24]
According to the [React docs](https://reactjs.org/docs/jsx-in-depth.html#booleans-null-and-undefined-are-ignored), bool children don't render. So from a strongly typed perspective, having a `bool` overload of `text`/`innerText` makes no sense. I suggest removing it.

**Comment by Zaid-Ajaj** [comment]
Done, thank you!
