### ISSUE TITLE
style.float is shadowing F# float

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#248]
Functions such as the following are taking a `style.float` instead of a normal `float`.

https://github.com/Zaid-Ajaj/Feliz/blob/b255bb25a22ce71e3eb02f4bb9d403fc2612b7b3/Feliz/Styles.fs#L2037

![image](https://user-images.githubusercontent.com/53196138/89750072-06a76180-da90-11ea-9ad3-ebc94f9a911a.png)

**Comment by Shmew** [comment]
Oh that's bad, whoops. I pushed out 1.12.1 to rename `style.float` to `style.float'`. Should be up soon.

**Comment by zanaptak** [comment]
Verified fixed.
