### ISSUE TITLE
Remove Guid overload of text/innerText(/children)

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#25]
The `Guid` overload of `text`/`innerText` simply calls `string` on the input and otherwise works just like the `string` overload. I suggest the `Guid` overload be removed, for the following reasons:

* The overload probably doesn't add that much convenience since it's not often you'd want to render a `Guid` as a string
* There is no one correct way to convert a `Guid` to `string`; several formats may be used (upper/lowercase, enclosed in brackets or not, with/without dashes)
* The `Guid` overload hides the fact that some processing takes place (and which processing that is)
* Calling `string` is very simple for the user to do themselves

(On the other hand, a `Guid` overload for `prop.key` makes more sense to keep.)

**Comment by Zaid-Ajaj** [comment]
You are right, I have removed it from prop.text and will probably remove `prop.innerText` altogether

**Comment by cmeeren** [comment]
Hm... After more research, I am thinking that perhaps anything that accepts `string` should also accept `Guid`. The reason is that a `Guid` is represented by a `string` (see [Fable compatibility docs](https://fable.io/docs/dotnet/compatibility.html)). So AFAIK there is actually no conversion; you can simply unbox a `Guid` as a `string` and it will always work, no extra processing involved.

What do you think?

**Comment by MangelMaxime** [comment]
It's dangerous to base your library implementation on the internal representation of the types. For example, yes today `Guid` is represented as `string` but nothing guarantee that tomorrow it will not be represented by a class.

I think it already happened in the past were decimal were represented using `string` or `number` and now we have a class for them and was even considered to use WebAssembly to represents them.

So even if you add `Guid` or `char` variant of the helpers, my advice is to avoid "hack" like `unbox` and use `guid.ToString()` or `string charValue`.

**Comment by Zaid-Ajaj** [comment]
@cmeeren The reasons for not using Guid is not because to save the computation of stringifying it but rather because of the points you mentioned above, it doesn't make much sense and for this example as well, I would rather wait for a good use-case where a user really needs this thing over calling `string guid`

**Comment by cmeeren** [comment]
Thanks for the clarifications, I agree with both of you. :)

**Comment by alfonsogarciacaro** [comment]
Yes, `Guid` is currently compiled as a string, but this (as other Fable _hacks_) is an implementation detail that may change in the future. Libraries shouldn't rely on this :)

However, I think before we used to erase the `String()` call when converting Guid to string, but it seems it's not the case now. We could try to do that again :)
