### ISSUE TITLE
Add Guid overload to prop.value (or make it completely generic)

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#26]
When using a `Select` in Material-UI, I needed to set the childrens' `value` to a `Guid` value (the ID of the entities to be selected). I suggest either adding a `Guid` overload to `prop.value` (and possibly other relevant primitives if any are missing), or simply having a single generic `'a` overload.

**Comment by Zaid-Ajaj** [comment]
Sounds good to me, I will add it soon after vacation. But if you can send a PR, that would be really great! (PRs are always welcome, for this issue and the others)

**Comment by cmeeren** [comment]
Great! I haven't sent any PRs because I don't know which of my issues you agree with. :) (And because a few of them overlap.)

**Comment by cmeeren** [comment]
Should I make it completely generic, or do you just want a `Guid` overload?

**Comment by Zaid-Ajaj** [comment]
I think just `Guid` is better because if you make it generic, it will accept `DateTime/bigint/long`, i would rather that the user decides how to put these in the Html. oh btw, I will add it ;)

**Comment by cmeeren** [comment]
This was closed by e13d597, but I can't see any `Guid` stuff in that commit.

**Comment by Zaid-Ajaj** [comment]
My bad, I added it in v0.44.0
