### ISSUE TITLE
[chore] Implement Feliz.Router using [<ReactComponent>]

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#272]
Publish a new version of Feliz.Router that uses latest Feliz to be able to apply the [<ReactComponent>] attribute

**Comment by Shmew** [comment]
Does using `React.functionComponent` not essentially apply this? Is that feasible? It would automatically enable any library using Feliz to automatically start using the plugin with just a version upgrade.

**Comment by Zaid-Ajaj** [comment]
Yeah you are right! I forgot to implement the plugin for `React.functionComponent` I believe it should be possible. Will take a look at shortly!

**Comment by Zaid-Ajaj** [comment]
Actually this isn't needed after all, only components written in the application itself seem be affected by the fast-refresh plugin
