### ISSUE TITLE
Q: How to format document?

### ISSUE THREAD

**Issue by KingKnecht** [Zaid-Ajaj/Feliz#287]
If I use fantomas to format my document I get a pretty hard to read format. E.g.:

![image](https://user-images.githubusercontent.com/4339172/100713015-f820e500-33b3-11eb-9d0b-8e264f590c3d.png)

becomes:
![image](https://user-images.githubusercontent.com/4339172/100713116-11c22c80-33b4-11eb-90e9-1c2717e7a7cb.png)

How do you format you documents? Manually?

Thx,
Sven

**Comment by Shmew** [comment]
This should be all you need for decent output now:

```
[*.fs]
fsharp_single_argument_web_mode=true
```

You can test out the settings using [this handy site](https://fsprojects.github.io/fantomas-tools/#/fantomas/v4).

**Comment by KingKnecht** [comment]
@Shmew That saved my life. I spent more time with formatting than with actual coding ;-)
For others:

- Make sure "EditorConfig" extension is installed.
- Right click in the source file tree, choose "Generate .editorconfig"
- Insert
`[*.fs]
fsharp_single_argument_web_mode=true`

be happy.

It would be nice to have the config globally. But haven't figured it out how to do that, yet.
