### ISSUE TITLE
Feliz.UseElmish should not include the generated JavaScript.

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#306]
When trying to use Feliz.UseElmish I had some weird error about file not being found under a `docs` folder.
 
- `/fableBuild/.fable/docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Option.js`
- `fableBuild/.fable/docs/.fable/Fable.Promise.2.0.0/Promise.fs.js`

While I don't have a `docs` folder in my project. It happens that Feliz.UseElmish is including the generated JavaScript file:

![image](https://user-images.githubusercontent.com/4760796/103468466-7da00800-4d59-11eb-8152-8bd4fddcb34d.png)

Which contains:

```js
import { Union } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Types.js";
import { class_type, union_type, int32_type, array_type } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Reflection.js";
import { fill } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Array.js";
import { isDisposable, comparePrimitives, max } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Util.js";
import { toArray, value as value_1, some } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Option.js";
import { iterate as iterate_1, rangeNumber, singleton, collect, take, skip, append, delay } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Seq.js";
import { useReact_useMemo_CF4EA67, useReact_useEffect_3A5B6456, useReact_useEffect_Z101E1A95, useReact_useEffect_Z5234A374, useReact_useCallbackRef_7C4B0DD6, React_createDisposable_3A5B6456, useReact_useEffectOnce_Z5ECA432F, useFeliz_React__React_useState_Static_1505, useReact_useRef_1505 } from "../Feliz/React.fs.js";
import { isCancellationRequested, cancel, createCancellationToken } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/Async.js";
import { promise } from "../docs/.fable/Fable.Promise.2.0.0/PromiseImpl.fs.js";
import { PromiseBuilder__While_2044D34, PromiseBuilder__Delay_62FBFDE1, PromiseBuilder__Run_212F1D4B } from "../docs/.fable/Fable.Promise.2.0.0/Promise.fs.js";
import { iterate } from "../docs/.fable/fable-library.3.0.0-nagareyama-rc-007/List.js";

export class RingState$1 extends Union {
    constructor(tag, ...fields) {
        super();
        this.tag = (tag | 0);
        this.fields = fields;
    }
    cases() {
        return ["Writable", "ReadWritable"];
    }
}

```

It should be enough to remove the `*/js` from the fsproj.

https://github.com/Zaid-Ajaj/Feliz/blob/05c5c608f9b60aaf543bdce065751c0fdf60bf0d/Feliz.UseElmish/Feliz.UseElmish.fsproj#L21

Or to had an exclude property I think `<Content Include="*.fsproj; **\*.fs; **\*.js" Exclude="**\*.fs.js" PackagePath="fable" />` could work or perhaps the include needs to be tweaked a bit more.

As a temporary work around, I delete manually the `.fs.js` file under the `.fable` folder and it appear that it force Fable to recompile it.

**Comment by Shmew** [comment]
Yeah the project doesn't need any JS, so we should probably just remove that inclusion (and any other fsproj that have `*.js` besides `Feliz` proper).

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @MangelMaxime for the suggestions. I just published a batch that excludes `.fs.js` from the nuget package
