### ISSUE TITLE
Support for pointer-events and touch-action

### ISSUE THREAD

**Issue by bzuu** [Zaid-Ajaj/Feliz#309]
Hi, it would be nice to have support for the [pointer-events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) and [touch-action](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) CSS properties. I'd be happy to submit a PR for this. The one thing I am not sure about is what to do with the SVG only values for pointer-events, e.g. `visiblePainted`. Should these be included? Should they somehow be marked as experimental?

**Comment by Shmew** [comment]
Since SVG is separated from the normal properties you can just copy and paste the `pointerEvents` type and then add the two additional lines (and change the attribute call on all of them of course).

**Comment by bzuu** [comment]
@Shmew thanks, I didn't realise the SVG stuff was separate (or even included at all). I was mostly wondering if the properties should be added or not for the HTML side of things as they are marked as experimental for HTML. Would it perhaps be a good idea to include all values for both HTML and SVG and mark them in HTML with the `Experimental`  attribute? Similar to [this](https://github.com/Zaid-Ajaj/Feliz/blob/bdf64d80f5bd3bb1b3821badb4ca0f98f07cb10a/Feliz/Styles.fs#L2207)?

**Comment by Shmew** [comment]
Yeah you can add them in HTML with the attribute (it doesn't do anything, it's just more for us), at least I don't see an issue. Normally I try to avoid APIs that are not fully supported, but in this case every browser supports it, and has for quite some time. @Zaid-Ajaj can give his thoughts, but I suspect he feels the same way.

**Comment by bzuu** [comment]
I am working on the PR for this, but while doing so I it seems like for SVG there is no support for any events as of yet or am I missing something? I can't find any Feliz SVG samples so perhaps I overlooked something.

As far as I can see  `prop.onClick` returns an `IReactProperty`, but the SVG elements expect `ISvgAttribute`. As the `pointerEvents` and `touchAction` properties which I am working on affect the event behaviour, it does perhaps not make a whole lot of sense to implement this for SVG right now?

**Comment by Shmew** [comment]
I believe those are different from the events you're thinking of, they should work for SVG.

**Comment by bzuu** [comment]
@Shmew like I said, perhaps I am missing something, but I don't see how to attach an `onClick` handler to an SVG element in Feliz. If you can't do that, it doesn't make sense to me to influence its behaviour with the `pointerEvents` attribute. I wouldn't even be able to test if the new attributes work.

If you could provide a sample of how to attach an `onClick` handler using Feliz to an SVG element, that would be much appreciated.

**Comment by Shmew** [comment]
This [blog post](https://www.smashingmagazine.com/2018/05/svg-interaction-pointer-events-property/) should help give you an idea of how this would be used with SVG.

**Comment by bzuu** [comment]
@Shmew thanks for the link, I really appreciate your help. Unfortunately this still does not help me. I am fully aware of how to do this with regular (non F#/Feliz) code. The problem is how to do it in **Feliz**. For example this won't work:
```F#
Svg.ellipse [
      svg.cx 240
      svg.cy 50
      svg.rx 220
      svg.ry 30
      svg.fill "yellow"
      prop.onClick (fun evt -> printfn "clicked") // This doesn't work
]
```
It tells me:
```
This expression was expected to have type
    'ISvgAttribute'    
but here has type
    'IReactProperty'
```
How should I attach an `onClick` handler to an **SVG element in Feliz**?

**Comment by MangelMaxime** [comment]
@bzuu I don't know what will be the decision of the maintainers of this project but you probably needs to duplication the `onClick` property to attach it to the `svg` type and make it return an `ISvgAttribute`.

https://github.com/Zaid-Ajaj/Feliz/blob/60b327072ebc45e78ba76b4c7d7daea546822175/Feliz/Types.fs#L3-L10

Because they are both currently independent types.

**Comment by bzuu** [comment]
@MangelMaxime thanks, this is indeed what I was wondering about. Your comment seems to confirm this currently isn't supported indeed.

Although I would be more than happy to give implementing this a shot, it seems a bit distant from my original issue. Perhaps we should create a separate issue for adding the onX handlers for SVG?

**Comment by MangelMaxime** [comment]
Yes indeed, creating a dedicated issue asking for handlers for SVG makes sense.

As for the current issue, if I was you I would create a PR adding `pointer-events` because it is already well supported by the browser and in the specification.

https://caniuse.com/?search=pointer-events

For `touch-action` the support is less robust currently. So I would wait for the maintainer to decide to add it or not.

For now, I would probably just add it locally to my project and share the code in this issue if someone else needs it. So he can copy/paste it in it's project :)

**Comment by bzuu** [comment]
Great, sounds like a plan. I'll create the issue and PR when I am near my pc.

**Comment by bzuu** [comment]
For anyone interested in an implementation for `touch-action` until it gets supported you can check this commit https://github.com/bzuu/Feliz/commit/8235ecf11e5ef3009583a1c1e56a3182a697ac37

**Comment by Shmew** [comment]
Sorry, looks like I was being a bit dense. What I was getting at was that regardless of if event handlers were properly implemented, the properties were still valid for SVG and so they could be added. Looks like you already created an issue for the handlers so that should cover that side of things.

**Comment by bzuu** [comment]
@Shmew, I see what you mean. In the current PR I haven't included the SVG side of things however. For now I think it is most straightforward to get the event support first, then add these attributes as well for SVG so it can be tested. I'll see if I can find some time to submit both other PR's some time this week.
