### ISSUE TITLE
Use Fable.React? (E.g. support for SSR)

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#31]
I notice that Fable.React has special handling of server-side rendering, e.g.

https://github.com/fable-compiler/fable-react/blob/fa43005e82490945e2a59beedf86054ae1e929a3/src/Fable.React.Helpers.fs#L336-L342

Since Feliz does not directly use Fable.React for creating components but instead imports stuff itself, it might seem that any features found in Fable.React is not available in Feliz.

Should Feliz delegate component creation (and any other relevant functionality that might come up) to Fable.React in order to take advantage of the specifics of the Fable.React implementation?

**Comment by Zaid-Ajaj** [comment]
I think the SSR implementation of Fable.React is one big mess both for applications and library maintainers with the use of compiler directives. There are no plans of supporting SSR the way Fable.React does for now. I believe there should be better ways for supporting it but SSR in Feliz is low-priority now

**Comment by cmeeren** [comment]
Gotcha, feel free to close.
