### ISSUE TITLE
Add event handlers for SVG

### ISSUE THREAD

**Issue by bzuu** [Zaid-Ajaj/Feliz#312]
Currently there seems to be no support for event handlers in SVG. See the discussion in #309. I'd be happy to implement this, but some input from the maintainers on this would be welcome as to what approach would be best:

* Duplicate the current code available for HTML elements
* Modify the existing code in some way to allow the event handlers to be used for both SVG and HTML elements
* ...

**Comment by Shmew** [comment]
I think it's probably easiest to just duplicate the code, in most cases it's a very simple `Interop.mkAttr "someAttribute" value`. We could do something like a shared type both `prop` and `svg` could inherit from but it makes things messy if one has an overload the other shouldn't.

**Comment by bzuu** [comment]
@Shmew thanks for sharing your thoughts on this. I think the duplication would be the most straightforward indeed and does as you say allow differentiation in situations when HTML and SVG are not completely aligned (if any).

**Comment by Zaid-Ajaj** [comment]
Resolved in #314
