### ISSUE TITLE
When using the template mentioned in the start guide errors are present in the console on running

### ISSUE THREAD

**Issue by 7sharp9** [Zaid-Ajaj/Feliz#328]
Template was the one mentioned in the docs: `dotnet new -I Feliz.Template`
```
[HPM] Error occurred while trying to proxy request /img/favicon-32x32.png from 127.0.0.1:8080 to http://localhost:5000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

Im assuming this is because of the dev environment and the web pack config in the template:

```
        // When using webpack-dev-server, you may need to redirect some calls
        // to a external API server. See https://webpack.js.org/configuration/dev-server/#devserver-proxy
        devServerProxy: {
            '/**': {
                // assuming the suave server is running on port 8083
                target: "http://localhost:5000",
                changeOrigin: true
            }
        },
```

**Comment by Zaid-Ajaj** [comment]
Hi there @7sharp9, thanks a lot for filing the issue. I have a look

I think this happens because the icon isn't found and then webpack falls back to `devServerProxy`. 

However, this part is really reserved for when you have a backend running alongside the frontend on `http://localhost:5000` and proxying the requests from `http://localhost:8080` .

**Comment by 7sharp9** [comment]
Im in the process of porting a site from Elm, so just looking at Feliz as the target, I was using express to host as it was quick and easy to setup and deploy.  Would you recommend something like that with Feliz?

**Comment by Zaid-Ajaj** [comment]
> Im in the process of porting a site from Elm, so just looking at Feliz as the target, I was using express to host as it was quick and easy to setup and deploy. Would you recommend something like that with Feliz?

Yeah for sure, you should be able to choose whatever backend you have and it should work. 

Let me know if you have questions along the way

**Comment by 7sharp9** [comment]
I wonder why the favicons would not be found?  They are in the list folder when you make a prod build.

**Comment by Zaid-Ajaj** [comment]
Because the `devServerProxy` decided to proxy every single HTTP request to the "backend" at `http://localhost:5000` but that is not what it should do because this template is frontend only and doesn't include a backend. 
```js
// When using webpack-dev-server, you may need to redirect some calls
// to a external API server. See https://webpack.js.org/configuration/dev-server/#devserver-proxy
devServerProxy: {
    '/**': {
        // assuming the backend is running on port 5000
        // so that every request starting with /api will be proxied here
        target: "http://localhost:5000",
        changeOrigin: true
    }
}
```
Should be
```js
// When using webpack-dev-server, you may need to redirect some calls
// to a external API server. See https://webpack.js.org/configuration/dev-server/#devserver-proxy
devServerProxy: {
    '/api*': {
        // assuming the backend is running on port 5000
        // so that every request starting with /api will be proxied here
        target: "http://localhost:5000",
        changeOrigin: true
    }
}
```
Notice the rule `/**` becomes `/api` so that the frontend will only proxy HTTP requests staring with `/api` to the backend during development

**Comment by 7sharp9** [comment]
Ah yeah, that makes sense, easy change, do you want me to update the template?

**Comment by Zaid-Ajaj** [comment]
> do you want me to update the template?

I just did 😉

**Comment by soycabanillas** [comment]
It seems that the commit SHA: f3886b4179b652b53ac74b428fadcd3539580a26 reintroduces this bug.
