### ISSUE TITLE
In the documentation for Elmish and Elmish components include the invocation from main code.

### ISSUE THREAD

**Issue by 7sharp9** [Zaid-Ajaj/Feliz#329]
If you are new to Feliz then having the code to invoke the Elmish style would be handy, for example on the `React Elmish Components section`:

```
open Feliz
open Feliz.UseElmish
open Elmish

type Msg =
    | Increment
    | Decrement

type State = { Count : int }

let init() = { Count = 0 }, Cmd.none

let update msg state =
    match msg with
    | Increment -> { state with Count = state.Count + 1 }, Cmd.none
    | Decrement -> { state with Count = state.Count - 1 }, Cmd.none

let counter = React.functionComponent(fun () ->
    let state, dispatch = React.useElmish(init, update, [| |])
    Html.div [
        Html.h1 state.Count
        Html.button [
            prop.text "Increment"
            prop.onClick (fun _ -> dispatch Increment)
        ]

        Html.button [
            prop.text "Decrement"
            prop.onClick (fun _ -> dispatch Decrement)
        ]
    ]
)
```

Its not clear on how you would invoke that from main, would you need to use something like makeElmishprogram or just use a ReactComponent like:

```
module Main

open Feliz
open Browser.Dom
open Fable.Core.JsInterop

importAll "./styles/global.scss"

ReactDOM.render(
    counter (),
    document.getElementById "feliz-app"
)
```

**Comment by 7sharp9** [comment]
It might also be worth mentioning when first talking about useElmish than it should be installed with `dotnet add package Feliz.UseElmish` just everything flows better rather than finding a missing reference.

**Comment by Zaid-Ajaj** [comment]
You would indeed just invoke the react component and the useElmish hook will take care of the dispatch loop

Consider using the new stuff from Fable 3

[< ReactComponent >]
let Counter() = 
  let state, dispatch = React.useElmish(...)
  Html.div [ ]

ReactDOM.render(Counter(), document.getElementById "feliz-app")

**Comment by Zaid-Ajaj** [comment]
I will be updating the docs soon to latest Fable 3 bits and address the confusing points

**Comment by 7sharp9** [comment]
Yeah Im just reading the docs as I try to fumble with Elmish :-/

**Comment by 7sharp9** [comment]
@Zaid-Ajaj Last question for today :-)  When using Feliz.Router do you still have to use the `Program.mkProgram` ?

**Comment by Zaid-Ajaj** [comment]
Nope, there isn't any global Program, just React components like Router.router component from the Felix.Router package. See the SAFE.React repo for more examples :)

**Comment by Zaid-Ajaj** [comment]
@7sharp9 I have updated [React Elmish Components](https://zaid-ajaj.github.io/Feliz/#/Hooks/UseElmish) to Fable 3 bits and added more bits about the dependencies array and resource disposal. Please have a look and let me know if anything is weird or confusing.
