### ISSUE TITLE
Nested React Components fails to compile

### ISSUE THREAD

**Issue by roboz0r** [Zaid-Ajaj/Feliz#331]
### Description

If a function tagged with `[<ReactComponent>]` calls another function also tagged with `[<ReactComponent>]` on the same line of code the compiler fails with the following message `EXCEPTION: Cannot find implementation file /`. If the component is bound to a value prior to being passed the compilation is successful. 

### Repro code

From the Felliz template I modified `App.fs` per below

    module App

    open Feliz

    [<ReactComponent>]
    let Comp3 (children:ReactElement) = Html.div [ children ]

    [<ReactComponent>]
    let Comp2 ()  = Html.h1 "Hello world"

    [<ReactComponent>]
    let HelloWorld() = 
        Comp3 (Comp2 ())

If `HelloWorld` is changed to:

    [<ReactComponent>]
    let HelloWorld() = 
        let comp2 = (Comp2 x)
        Comp3 comp2

Then the code is able to compile. 

### Expected and actual results

Expected: The code compiles.
Actual: Fable compiler reports the following `C:/Projects/Feliz Template/src/App.fs(1,1): error EXCEPTION: Cannot find implementation file /`

### Related information

* Fable version: Fable: F# to JS compiler 3.1.10 
* Operating system: Windows 10. Compiling through VS Code powershell terminal. 

    Feliz Version="1.37.0"
    Feliz.Router Version="3.7.0"
    Fable.DateFunctions Version="3.7.0"

**Comment by roboz0r** [comment]
Cross posted on the Fable repo as not sure where the error lies https://github.com/fable-compiler/Fable/issues/2412

**Comment by Zaid-Ajaj** [comment]
Hi @roboz0r, this does look like a Fable error since it is coming from the compiler. I will test it locally to see maybe see what is going on. Maybe Fable is having trouble with the order of applying the transformations

**Comment by alfonsogarciacaro** [comment]
I thought this was an issue with Fable as well ;) but after checking a lot I realized this was caused because the plugin is creating its own EntityRef with `SourcePath "/"` so when Fable finds it cannot find the actual entity https://github.com/Zaid-Ajaj/Feliz/blob/88e0d1b1fe1db5ce9fc047be3ab393c9df42b2e1/Feliz.CompilerPlugins/AstUtils.fs#L63-L66

In this case, in order to create the ReactElement type, the easiest way is to take it directly from the expression passed to the plugin. I've sent PR #333 to fix it 👍

**Comment by Zaid-Ajaj** [comment]
Published Feliz v1.38 which should include the fix. @roboz0r can you please give it a try and confirm that it is fixed?

**Comment by roboz0r** [comment]
Tested and working. Thanks @alfonsogarciacaro and @Zaid-Ajaj :)
