### ISSUE TITLE
pigeon-maps breaking change

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Feliz#335]
`pigeon-maps` released a new version a few days ago that breaks the bindings. We do an [importDefault](https://github.com/Zaid-Ajaj/Feliz/blob/master/Feliz.PigeonMaps/PigeonMaps.fs#L24), and they [got rid of the default export](https://github.com/mariusandra/pigeon-maps/commit/1c098836d6fe128660c4187bfecb64ccf9bfa422#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405).

**Comment by Zaid-Ajaj** [comment]
Darn it, even though the original library introduced a major change in a new release, the binding shouldn't break when installed via Femto but I had the ResolutionStrategy set to max instead of min :/

**Comment by Zaid-Ajaj** [comment]
Fixed as of  Feliz.PigeonMaps v2.5
