### ISSUE TITLE
Aliasing Props page in docs is broken

### ISSUE THREAD

**Issue by olivercoad** [Zaid-Ajaj/Feliz#339]
Just noticed the https://zaid-ajaj.github.io/Feliz/#/Feliz/React/Feliz/Aliasing page in the docs is broken.

`Status 404: could not load markdown`

**Comment by Zaid-Ajaj** [comment]
Thanks for filing the issue @olivercoad I'll fix it later tonight

**Comment by Zaid-Ajaj** [comment]
Should now be fixed
