### ISSUE TITLE
Wrapper for MSAL

### ISSUE THREAD

**Issue by dwlizlo** [Zaid-Ajaj/Feliz#349]
Would Feliz be good fit to create wrapper for React MSAL? I've seen there are couple of wrappers for projects like SignalR for example.

**Comment by Zaid-Ajaj** [comment]
Yeah absolutely, a Feliz wrapper for React msal would be great. I haven't used that library so I am not how difficult it is to build the binding but would be happy to help create one 💯

**Comment by AlbertoDePena** [comment]
I gave that a shot a while back... Take a look at this repo for some inspiration =)

https://github.com/AlbertoDePena/Fable.Msal

**Comment by Zaid-Ajaj** [comment]
As mentioned above, there is now already a library for this which is a single file that can also be adapted into your project as you see fit
