### ISSUE TITLE
Method on Childcomponent

### ISSUE THREAD

**Issue by brase** [Zaid-Ajaj/Feliz#350]
I am not sure if I am thinking correct but is it possible to somehow call a method on a component to update its state? I am thinking of a modal component using the useElmish hook internal which I want to open with a function call from the parent to dispatch the open message.
Is it possible to achieve this with Feliz?

**Comment by Zaid-Ajaj** [comment]
Yes it is possible, I believe the approach with React modals is not so much to "show them in function call" but rather use a boolean flag to determine when to show/hide the model and the modal component will take an `onClose` handler:
```fs
[<ReactComponent>]
let Modal(onClose: unit -> unit) = ...

[<ReactComponent>]
let Page() = 
  let (modalShown, showModal) = React.useState(false)
  Html.div [
      if modelShown then Modal(fun _ -> showModal false)
      Html.button [
          prop.text "Show Modal"
          prop.onClick (fun _ -> showModal true)
      ]
  ]
```

**Comment by brase** [comment]
>  I believe the approach with React modals is not so much to "show them in function call" 

Ah I see. Thank you  so much. I already thought of doing something wrong.

Sorry for disturbing you.

**Comment by Zaid-Ajaj** [comment]
No worries at all! You can always ask questions here 😄 btw things like "how do you do X in Feliz?" almost 90% of time boils down to "how to do X in React?" and then translating the code. You will probably find a lot more examples and tutorials for the latter 😉

**Comment by brase** [comment]
Yes of course. I already did that a lot. The thing is when you on a wrong path and the community is big enough you'll find someone who did it the wrong way. That was the reason for creating the issue cause I found a lot of weird react solutions.

**Comment by brase** [comment]
Just found this:

```js
import React from 'react';

class UserAction extends React.Component {
    constructor(props) {
        super(props)

        this.state = {
            isLoggedIn : false
        }
    }

    toggleLogin = () => {
        this.setState({isLoggedIn: !this.state.isLoggedIn})
    }

    render() {
        return (
            <div>
                <h1>User is {this.state.isLoggedIn ? 'Logged In' : 'Not Logged In'}</h1>
                <button onClick={this.toggleLogin}>{this.state.isLoggedIn ? 'Log Out' : 'Log In'}</button>
            </div>
        );
    }
}

export default UserAction;
```

Is `toggleLogin` an anti pattern? Does Feliz support something like this?

**Comment by Zaid-Ajaj** [comment]
Hi @brase,

Why would `toggleLogin` be an anti-pattern? I think this just an example to show you how boolean flags/state variables can be used 

In Feliz, you can create stateful components like this:
```fs
open Feliz

[<ReactComponent>]
let UserAction() = 
  let (isLoggedIn, setLoggedIn) = React.useState false
  Html.div [
      Html.h1 (if isLoggedIn then "Logged In" else "Notlogged in")
      Html.button [
          prop.text (if isLoggedIn then "Log Out" else "Log In")
          prop.onClick (fun _ -> setLoggedIn(not isLoggedIn))
      ]
  ] 
```

**Comment by brase** [comment]
Ah yes, of course. But calling `toggleLogin` from parent would be an anti pattern?

**Comment by Zaid-Ajaj** [comment]
I don't see any parent component in the example above 😅 

You don't/can't call `toggleLogin` from the parent, but the parent _can react_ to the flag being switched when the parent component passes a _callback_ for when users login
```fs
[<ReactComponent>]
let Login(onLogin: User -> unit) = ...

[<ReactComponent>]
let UserProfile(user: User) = ...

[<ReactComponent>]
let App() = 
  let (currentUser, setCurrentUser) = React.useState<User option>(None)
  match currentUser with 
  | None -> Login(fun user -> setCurrentUser (Some user))
  | Some user -> UserProfile(user)
```

**Comment by brase** [comment]
If I annoy you just ignore me.

Here is an complete example I found:

https://github.com/akiran/react-slick/blob/5fb7ac78321f3469118a974af3852742b64fcbd3/examples/PreviousNextMethods.js

And while writing this I see, these methods are being accessed through using a ref hook. Okay, now I got it. Is this legit or more an anti pattern?

**Comment by Zaid-Ajaj** [comment]
I wouldn't say it is an anti-pattern. React components are _declarative_ by design so if you want to control the underlying component using imperative methods such as `slideNext()` and `slidePrev()` then using `ref` is the way to go since it gives you access to the underlying lower-level instance of the slider which has these methods attached to it.

**Comment by brase** [comment]
Is it possible to write such a component with Feliz?

**Comment by Zaid-Ajaj** [comment]
Of course, Feliz supports [React References](https://zaid-ajaj.github.io/Feliz/#/Feliz/React/Refs) for this example, you would need to create your own reference hook such as `React.useSliderRef()` and set it in the `ref` property of the component. 

The example in the docs show you how to call the imperative `focus()` function of an input. The idea is the same with the slider, though the types are different because the latter has methods `slideNext()` and `slidePrev()`

**Comment by brase** [comment]
Yes, I know. But I was wondering how do I define such a compenent in Feliz. I mean a component with functions which are accessable with the help of the ref hook.
 Is there an api for something like a class component? I don't know if I'll ever need this but I'm interested to see if it can be done with Feliz.

**Comment by Zaid-Ajaj** [comment]
The linked the React references guide above which shows you a component that has access to the `focus()` method via a React ref hook. The idea is that same here. Feliz supports class components (Fable.React actually does and Feliz depends on it) but the modern React patterns recommend using function components i.e. with `[<ReactComponent>]`

**Comment by brase** [comment]
Thank you!
