### ISSUE TITLE
Form validation

### ISSUE THREAD

**Issue by dwlizlo** [Zaid-Ajaj/Feliz#356]
Having form validation for Feliz would be nice :)

**Comment by Zaid-Ajaj** [comment]
Hi @dwlizlo you can already implement form validation with Feliz, what exactly are you missing? 🤔

**Comment by dwlizlo** [comment]
Hey @Zaid-Ajaj I'm looking for something similar to react-hook-form.
I assume you mean implementing validation myself along with storing state? I can try this, I'm just a bit worried about boilerplate though.

**Comment by Zaid-Ajaj** [comment]
I would say give it a try yourself before looking into helper libraries. I have seen `react-hook-form` before and building a binding for it might not the most straightforward thing so for now use what you know, a couple of state variables can go along way!
