### ISSUE TITLE
Add prop.onFocusOut

### ISSUE THREAD

**Issue by dwlizlo** [Zaid-Ajaj/Feliz#357]
Hey, prop seem to be missing onFocusOut (only onFocus is available)

**Comment by Zaid-Ajaj** [comment]
Hi @dwlizlo according to latest [react source-code](https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js#L34-L42), onFocusOut is not supported and onBlur should be used instead
