### ISSUE TITLE
Incompatible Markdown version

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Feliz#373]
Trying to install Feliz.Markdown ran into an issue with the NPM:

npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0" from react-markdown@4.3.1
npm ERR! node_modules/react-markdown
npm ERR!   react-markdown@"^4.3.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

The latest version of react-markdown is 6.0.2, however that is not compatible anymore with Feliz.Markdown.

**Comment by Zaid-Ajaj** [comment]
Hi @halcwb it looks like we need to update Femto metadata of Feliz.Markdown because it needs an older version of React. 

In the meantime, you can update react-markdown to a more recent version until this issue is fixed

**Comment by Zaid-Ajaj** [comment]
Fixed as of 
 - Feliz.Markdown v2.3.0 (for Fable v4)
 - Feliz.Markdown v1.7.0 (for Fable v3)

Now requiring `8.0.4 <= react-markdown < 9.0.0`
