### ISSUE TITLE
Remove Obselete warning on Html.title

### ISSUE THREAD

**Issue by MangelMaxime** [Zaid-Ajaj/Feliz#383]
When using `Html.title` there is a warning 

> Html.title is obsolete for creating <title> SVG elements, use Svg.title instead

https://github.com/Zaid-Ajaj/Feliz/blob/5256d3ca65e54675b2730734d1417aaf4d81c365/Feliz/Html.fs#L789-L797

However, `Html.title` is perfectly valid when generate `<title>My page title</page>` element tag.

https://www.w3schools.com/tags/tag_title.asp

**Comment by Zaid-Ajaj** [comment]
Removed the obsolete warning as of Feliz v1.48 🚀 thanks @MangelMaxime for reporting the issue
