### ISSUE TITLE
Need tips on overload resolution

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#39]
In Feliz.MaterialUI, I have a prop ([`Slider.step`](https://material-ui.com/api/slider/)) which can be a `number` or `null`. Both ints and floats are relevant.

I currently have this:

```f#
type slider =
  static member inline step(value: int) = Interop.mkAttr "step" value
  static member inline step(value: float) = Interop.mkAttr "step" value
  static member inline step(value: int option) = Interop.mkAttr "step" value
  static member inline step(value: float option) = Interop.mkAttr "step" value
```

This works great in the following examples:

```f#
slider.step 0.5
slider.step (if model.X then Some 2 else None)
```

But overload resolution fails in the following example:

```f#
slider.step None
```

A workaround is to write

```f#
slider.step (None: int option)
```

which I don't like since it's user-facing.

I can also implement one of the `option` members as an extension member, but I'd rather not if it can be helped (would complicate the generator). Might turn out to be best, though.

Just wondering if you have a tip on how to best handle API design in these cases.

**Comment by Zaid-Ajaj** [comment]
In this case I would try to simplify the API based the use-case: does the user/developer ever need to put `null` in there, isn't that just omitting the property all together? if that is the case I would only consider `int` and `float` overloads and remove the `optional` overloads. 

I think it will be easier in future versions of F# when it supports implicit yields in lists:
```fs
Slider.slider [
  if model.X then yield slider.step 10
  slider.value model.Y
]
```

**Comment by cmeeren** [comment]
Unfortunately, for `slider.step`, the default is `1` so the user must explicitly pass `None`.

**Comment by MangelMaxime** [comment]
You can also decide to only support the most generic case aka `float` and `float option`.

**Comment by cmeeren** [comment]
I ended up implementing the `float option` overload as an extension member. That way, this will "just work" for users. Thanks for the suggestions!
