### ISSUE TITLE
What is the purpose of [<Erase>] in Feliz?

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#40]
I notice that some types have `[<Erase>]` (but not all; notably, not `prop`).

https://github.com/Zaid-Ajaj/Feliz/search?q=%5B%3CErase%3E%5D&unscoped_q=%5B%3CErase%3E%5D

What is the point of `[<Erase>]` when members are generally inline anyway?

I'm asking because I need to know what to `[<Erase>]` in Feliz.MaterialUI, if anything.

**Comment by MangelMaxime** [comment]
This is to reduce the impact of Feliz to bundle size to the minimum.

More info here: https://github.com/Zaid-Ajaj/Feliz/issues/1#issue-470762796

**Comment by cmeeren** [comment]
Thanks! Shouldn't it be on all types, then? E.g. `props`?

**Comment by MangelMaxime** [comment]
No, because prop contains at least one member that is not inlined: [Souce](https://github.com/Zaid-Ajaj/Feliz/blob/7b923171c17091dcd611a5e73aceabf789ee8edb/src/Properties.fs#L246)

Because inlining, this member would have a worst impact compare not inlined version.

**Comment by cmeeren** [comment]
Ah, so the general rule in the context of Feliz is "erase only types where ALL members are inline"?

**Comment by MangelMaxime** [comment]
Yes, in theory, this rule should in 98% (not a precise number 😉 ) reduce the final bundle size.

You can always use the REPL if unsure or look at the webpack size output.

**Comment by cmeeren** [comment]
Great, thanks!
