### ISSUE TITLE
Data list - input prop.list missing

### ISSUE THREAD

**Issue by StuwiiDev** [Zaid-Ajaj/Feliz#405]
Hi,

I have recently tried to use the Html.datalist and I found that when using the Html.Input to bind them together there is no 'list' prop on the Input.

Example

```
Html.input [
    prop.type' "text"
    prop.name "example"
    prop.list "exampleList" <-- Error here because list does not exist
]
Html.datalist [
    prop.id "exampleList"
    prop.children [
        Html.option [
            prop.value true
            prop.text "A
        ]
        Html.option [
            prop.value true
            prop.text "B
        ]
    ]
]
```

Is this something that could be added please or point me in the right direction if I have missed something.

Thanks

**Comment by MangelMaxime** [comment]
Hello @StuwiiDev,

While waiting for a fix you can use `prop.custom("list", "exampleList")`

`prop.custom` allows you to pass anything you want to the props.

**Comment by StuwiiDev** [comment]
ah didn't see that one! I'm very new to Fable and Feliz, 
Thanks for pointing that one out and the quick response, works a charm :)

**Comment by Zaid-Ajaj** [comment]
@StuwiiDev Updating Feliz to v1.52 should now include the missing property
