### ISSUE TITLE
Feliz.svg missing mask attribute

### ISSUE THREAD

**Issue by duncanworthy** [Zaid-Ajaj/Feliz#428]
I can see that the Svg type has the mask element mapped, but there doesn't appear to be the mask attribute mapping defined.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/mask

**Comment by duncanworthy** [comment]
Also just noticed there seems to be a copy-paste error on the mask element definition, as that seems to be mapped to "marker"

**Comment by Zaid-Ajaj** [comment]
Thanks for the PR, this should be resolved now (fix included from #429)
