### ISSUE TITLE
[Feliz.Rechart] Add Y tick label formatting 

### ISSUE THREAD

**Issue by zelenij** [Zaid-Ajaj/Feliz#436]
Looks like there is no way to format tick labels in Line charts (tickFormatter not on the API).  So using thousand separators, or having some smarter formatting is not directly possible at the moment.  https://github.com/recharts/recharts/issues/1534

**Comment by danne931** [comment]
Fixed with: https://github.com/Zaid-Ajaj/Feliz/pull/625
