### ISSUE TITLE
Add prop documentation

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#44]
Most props do not currently have documentation. The [MDN HTML attribute reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes) contains a short description for each attribute. Perhaps that, or something like it, could be added?

**Comment by Zaid-Ajaj** [comment]
> Perhaps that, or something like it, could be added?

Of course! that was my idea from the beginning, though I wanted to stabilize the API first

**Comment by Shmew** [comment]
I went through and added documentation to most of the props, there were a few that I couldn't so @Zaid-Ajaj will have to add those, or point me in the right direction.

**Comment by Zaid-Ajaj** [comment]
This issue is pretty much resolved thanks to you @Shmew :heart: if we forgot a property or two, that is fine for now because most of them now have proper docs! Maybe we can now focus on #75, @Shmew if you could take a stab it, would be really great!

**Comment by Zaid-Ajaj** [comment]
Forgot to close :smile:
