### ISSUE TITLE
Feliz.Markdown needs updating

### ISSUE THREAD

**Issue by halcwb** [Zaid-Ajaj/Feliz#451]
I think that the Feliz.Markdown binding needs an update as the version used, 4.2.2, is no longer compatible with the latest react. The latest react-markdown had some breaking changes: https://github.com/remarkjs/react-markdown/blob/main/changelog.md.

**Comment by halcwb** [comment]
P.S. The biggest breaking change is that `source` is not `children`.

**Comment by Zaid-Ajaj** [comment]
Fixed as of 
 - Feliz.Markdown v2.3.0 (for Fable v4)
 - Feliz.Markdown v1.7.0 (for Fable v3)
