### ISSUE TITLE
npx create-feliz-app

### ISSUE THREAD

**Issue by jkone27** [Zaid-Ajaj/Feliz#457]
would it be maybe useful for fable/react community to have a similar command also from npx (also installing other required dependencies, etc) or is this not useful/feasible to increase comunity adoption?

ps i know you can create it with ```dotnet new```, but i thought most js developers would prob be more comfortable with ```npx create-x``` ?

**Comment by jkone27** [comment]
https://github.com/facebook/create-react-app/issues/9060

**Comment by Zaid-Ajaj** [comment]
I think given that Feliz users are using F# with the dotnet SDK, they should easily be able to run two commands:
```
dotnet new -i Feliz.Template
dotnet new -n my-app
```
