### ISSUE TITLE
Feliz 1.60.0 has a <4.8.0 restriction on FSharp.Core

### ISSUE THREAD

**Issue by thinkbeforecoding** [Zaid-Ajaj/Feliz#464]
Previous version of Feliz have a restriction on FSharp.Core:  >= 4.7.2, but latest version (1.60.0) adds a new restriction < 4.8.0 on it.
This is incompatible with other versionning like Feliz.Bulma.Tooltip that has a >= 5.0.0 restriction on FSharp.Core

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for reporting the issue @thinkbeforecoding, should be fixed as of v1.61 🚀
