### ISSUE TITLE
Uncaught ReferenceError: React is not defined

### ISSUE THREAD

**Issue by arthur-s** [Zaid-Ajaj/Feliz#486]
Thanks for Feliz!
I have an issue with 3rd party React component integration. I've a self-written js component in `./js/Modal.js`:

```javascript
import { useEffect, useRef } from "react";
import { useState, useLayoutEffect } from 'react';
import { createPortal } from 'react-dom';
import { CSSTransition } from "react-transition-group";

function Modal({ children, isOpen, handleClose }) {
 // content
}
export default Modal;
```

I import it in F# code as:

```fsharp
module Messages
// imports

[<ReactComponent(import="default", from="./js/Modal.js")>]
let Modal (isOpen:bool) (handleClose: bool -> unit) (children: Feliz.ReactElement) = React.imported()

// this also didn't help:
//let Modal (isOpen:bool) (handleClose: bool -> unit) (children: Feliz.ReactElement) = 
//    let properties = ["isOpen" ==> isOpen; "handleClose" ==> handleClose; "children" ==> children]
//    Interop.reactApi.createElement(importDefault "./js/Modal.js", createObj !!properties)
```
It works when I include react's script into index.html:

```
<script src="/js/react.development.js">
<script src="/js/react-dom.development.js">
```
But if I don't use this scripts, I got an error: `Uncaught ReferenceError: React is not defined`.

How to properly import custom react component? (I don't want to port a `.js` component into `.fs`)

**Comment by Zaid-Ajaj** [comment]
Hi @arthur-s can you please show where this error is coming from exactly? As in the stack trace of the error because based on your information I don't see why it would result in error `Uncaught ReferenceError: React is not defined`

**Comment by arthur-s** [comment]
Hi @Zaid-Ajaj ,
I discovered next:

If component returns string, then it works, but if it returns JSX, then doesn't:
```
function Modal({ children, isOpen, handleClose }) {
    // works
    return (
        ""
	);
}

function Modal({ children, isOpen, handleClose }) {
    // doesn't work:
    return (
        <span>Hello</span>
	);
}
```

**Comment by arthur-s** [comment]
Ok, I've fixed it using `pragma` option for @babel/preset-react. I use next config:
```
["@babel/preset-react", {
                "development": isDevelopment,
                "pragma": "createElement" }]
```
And in order to make it work, I also need to include `createElement` in js module:
```
import { createElement } from "react";
```
