### ISSUE TITLE
Complete API implementation for hooks from React 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#50]
Complete API implementation for hooks from React, see [API Reference](https://reactjs.org/docs/hooks-reference.html)

### Basic Hooks
- [x] `React.useState`
- [x] `React.useEffect` 
- [x] `React.useContext`
### Additional Hooks
 - [x] `React.useReducer`
 - [x] `React.useCallback`
 - [x] `React.useMemo`
 - [x] `React.useRef`
 - [x] `React.useLayoutEffect`
 - [x] `React.useDebugValue`
 - [ ] `React.useImperativeHandle`

Suggestions/ideas/PRs with the implementation of these is very much welcome and highly appreciated 🙏

**Comment by cmeeren** [comment]
See https://github.com/fable-compiler/fable-react/commit/fa43005e82490945e2a59beedf86054ae1e929a3 for a discussion of Forcing `option`-wrapping of the ref hook's `current` value.
