### ISSUE TITLE
Missing Recharts properties

### ISSUE THREAD

**Issue by sydsutton** [Zaid-Ajaj/Feliz#516]
Hello, 

I have recently added some properties that I needed for Recharts.tooltip, barChart, and labelList to a project of mine. Would it be okay if I created a PR with those added so that you can review them? 

Thanks.

**Comment by Zaid-Ajaj** [comment]
> I have recently added some properties that I needed for Recharts.tooltip, barChart, and labelList to a project of mine. Would it be okay if I created a PR with those added so that you can review them?

Yes please! Contributions are always welcome 🙏

**Comment by sydsutton** [comment]
> Yes please! Contributions are always welcome 🙏

Great, thank you. PR sent! Please double check tooltip.position-- that one was tricky for me.

**Comment by sydsutton** [comment]
Just so you know, Zaid, I just fixed some build errors in the PR but am still unsure of tooltip.position. I'm not sure how to set the default position based on the parent element/ mouse position. Thanks again.

**Comment by Zaid-Ajaj** [comment]
Resolved as of Feliz.Recharts v3.15 (in case using Feliz v1.68) or latest v4.0 when using Feliz v2.0 🚀
