### ISSUE TITLE
Missing `prop.label` ?

### ISSUE THREAD

**Issue by sergey-tihon** [Zaid-Ajaj/Feliz#536]
`optgroup` has the attribute `label` but I cannot find it in Feliz.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup

It is missing one?

**Comment by Zaid-Ajaj** [comment]
Thanks for bringing this to my attention @sergey-tihon 🙏 added to Feliz v2.2.0 and will be soon available on nuget
