### ISSUE TITLE
Vite Support

### ISSUE THREAD

**Issue by jkone27** [Zaid-Ajaj/Feliz#542]
would it be possible to have Vite instead of webpack, it might remove a lot of additional not/required complexity?  or a template option for vite

**Comment by MangelMaxime** [comment]
Feliz is compatible with any JavaScript bundler.

Example of a minimal Vite config:

```js
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [react()],
    server: {
        watch: {
            ignored: [
                "**/*.fs"
            ]
        }
    }
})
```

Gitpod template: https://github.com/MangelMaxime/template-gitpod-fable-3-vite-react

**Comment by mrakgr** [comment]
@jkone27 I made a [SAFE Stack template](https://github.com/mrakgr/SAFE-Stack---Vite-Template) for Vite. I even made a video in the linked playlist on how to set it up from scratch.

**Comment by Zaid-Ajaj** [comment]
Feliz.Template v4.x is out 🚀 simplified a lot to use vite instead of webpack and latest Fable/Feliz bits
