### ISSUE TITLE
Trying to create a IReactProperty in FSI crashes

### ISSUE THREAD

**Issue by EverybodyKurts** [Zaid-Ajaj/Feliz#553]
I have an fsx script that crashes whenever I send it to FSI. The contents are the following:

```fsharp
#r "nuget: Feliz"

open Feliz

let property1: IReactProperty = prop.className "foo"
```
It results in the following error:

```fsharp
System.InvalidCastException: Unable to cast object of type 'System.Tuple`2[System.String,System.Object]' to type 'Feliz.IReactProperty'.
```

I'm using F# 7.0 and Feliz 2.4.0

**Comment by Zaid-Ajaj** [comment]
Hi @EverybodyKurts Feliz is a library which only works in F# projects that are compiled to JavaScript using [Fable](https://github.com/fable-compiler/Fable). FSI sessions don't know to compile the code to JS so this behaviour is expected. 
If you are looking for a view engine to render HTML that works on both on client _and_ server, then I suggest using [Feliz.ViewEngine](https://github.com/dbrattli/Feliz.ViewEngine) but there are others as well 😄
