### ISSUE TITLE
Component-specific props and using generator for core Feliz components/props

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#56]
I know you have said before that for the native DOM surfaced in Feliz, it makes sense to have all props be accessible in `props`. But I have been looking at the [MDN HTML Attribute reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes), and it seems that actually most attributes are specific to one or a handful of HTML elements.

I would therefore like to propose a similar solution as with Feliz.MaterialUI: Use component-specific props. The usage would be like this:

```f#
Html.form [
  form.accept "foo"  // only valid on form/input
  form.action "https://example.com/submit"  // only valid on form
  form.autocapitalize.sentences  // inherited, allowed on any HTML element
  form.children [
    // ...
  ]
]
```

In the example above, I make use of `accept` (only valid on `form` and `input`) and `action` (only valid on `form`). The `autocapitalize` prop is global (allowed for any HTML element, even unknown). I don't know whether `children` is valid for all HTML elements (e.g. maybe not `input`?), so it's added directly to `form` (if this is wrong, `children` should be global and inherited everywhere, making the usage identical anyway).

In order to make this possible to maintain, Feliz.Generator can be used. To play around with an example, see Feliz.MaterialUI's `generate-native-dom` branch, in particular the project [Feliz.Generator.CoreDom](https://github.com/cmeeren/Feliz.MaterialUI/tree/generate-native-dom/src/Feliz.Generator.CoreDom) which I just created to demo this. Specifically, [Program.fs](https://github.com/cmeeren/Feliz.MaterialUI/blob/4b5e36de6165f551f61b4da0f2f5638be0c5ede0/src/Feliz.Generator.CoreDom/Program.fs) contains the component/prop API definition (with some helpers to indicate how common logic can be factored out), and [OUTPUT_PROPS.fs](https://github.com/cmeeren/Feliz.MaterialUI/blob/4b5e36de6165f551f61b4da0f2f5638be0c5ede0/src/Feliz.Generator.CoreDom/OUTPUT_PROPS.fs) and [OUTPUT_COMPONENTS.fs](https://github.com/cmeeren/Feliz.MaterialUI/blob/4b5e36de6165f551f61b4da0f2f5638be0c5ede0/src/Feliz.Generator.CoreDom/OUTPUT_COMPONENTS.fs) contains the generator output.

Some benefits of using Feliz.Generator:
* It's easy to "inherit"/duplicate props as shown above, which again makes it easier for users to only use valid props
* If we need to change how Feliz components/props are implemented, that can be done once (in Feliz.Generator), and the API definition is still the same. No need to manually update hundreds of props/components if needing to change implementation details. This has helped me greatly in Feliz.MateriaUI so far while experimenting with different ways of doing inheritance etc., which would be next to impossible without it (imagine if I had manually rewritten thousands of lines of props only to then find out that F# type aliasing stops working properly if there are too many aliases).
* A library with the [components](https://github.com/cmeeren/Feliz.MaterialUI/blob/4b5e36de6165f551f61b4da0f2f5638be0c5ede0/src/Feliz.Generator.CoreDom/Program.fs#L30-L71) can be published separately, or at least referred to directly in 3rd party projects, so that it's less maintenance to include core Feliz props in e.g. Feliz.MaterialUI components.
* Automatic handling of `[<Erase>]` based on whether all members are `inline`
* Consistent formatting of output (for those who care about that)

Note: I have no idea how large the output files will be or which impacts it will have on compilation time. Feliz.MaterialUI currently has 7500 lines of props and 1000 lines of components, and I haven't noticed any slowdowns during Fable compilation. But it may of course be that the number of props, when "inherited"/dupliated, becomes too large to be feasible. For example, the MDN page I looked at does not list any event handlers, where AFAIK most are defined for any HTML element. So that'll be quite a bit of duplication.

What do you think? Feel free to disagree, of course. I'm completely open to this being a bad idea. Personally I'm fine with using `prop` and simply having to RTFM to know which props are valid where. In most common cases I think devs will know it already anyway,

**Comment by Zaid-Ajaj** [comment]
I will check out the generator thoroughly soon, to see what we can do with it
