### ISSUE TITLE
Feliz.Template v4.3.0 doesn't contain any tests

### ISSUE THREAD

**Issue by EverybodyKurts** [Zaid-Ajaj/Feliz#566]
When initiating a new project with `Feliz.Template` v4.3.0, the readme includes a section for testing the app:

---
### Tests

The template includes a test project that ready to go which you can either run in the browser in watch mode or run in the console using node.js and mocha. To run the tests in watch mode:
```
npm run test:live
```
This command starts a development server for the test application and makes it available at http://localhost:8085.

---

However, no `tests` directory or project is included with the template and there is no configuration specified for the `tests` object in `package.json`.

Would it make sense to include the test project form the previous version with the necessary updates?

**Comment by Zaid-Ajaj** [comment]
> When initiating a new project with Feliz.Template v4.3.0, the readme includes a section for testing the app: [...]

Hi @EverybodyKurts this piece from the README must be leftover from the last template.

> Would it make sense to include the test project form the previous version with the necessary updates?

 I realized that maintaining the template including all bells and whistles is a lot of work and takes a lot longer to improve. 

The alternative is that I've documented in detail how to add a test project from a Fable project in [Fable.Mocha](https://github.com/Zaid-Ajaj/Fable.Mocha) which is up to date and should be fairly easy to add to your project (whether using Feliz or not)

**Comment by kurt-mueller-osumc** [comment]
Hey Zaid, I can use the tests from `Fable.Mocha`. My only question is does it matter if the `Fable.Mocha` repo is using webpack while the new `Feliz.Template` is using vite?

**Comment by MangelMaxime** [comment]
@kurt-mueller-osumc In theory, no it doesn't matter.

For things like that, it is best to search how it is done in JavaScript to see if this is doable. Anything done in JavaScript should be doable with Fable and looking for help in JavaScript gives you access to a broader base of knowledge.
