### ISSUE TITLE
Feliz.Markdown and comment blocks

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Feliz#57]
If you use the * operator in a partial function like 

```
[0..3] |> List.map ((*) 5)
```
It causes the rest of the file to be washed out due to it thinking it's a comment.

An example [here](https://shmew.github.io/Feliz.Plotly/#/Plotly/Charts/Bubble/MarkerSizeColorAndSymbolArray)

**Comment by MangelMaxime** [comment]
The problem is `(*` because it's the starting block for comment in F#.

I don't think any grammar based on regex can handle this case correctly.

**Comment by Zaid-Ajaj** [comment]
It is actually a limitation of `react-highlight`, not `react-markdown` but the fix is as easy as expanding the point-free expression into a plain old function:
```fs
[0..3] |> List.map (fun x -> x * 5)
```

**Comment by Shmew** [comment]
Yeah I can just adjust the example, closing since it's a problem with `react-highlight`
