### ISSUE TITLE
More Recharts examples

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#58]
Help make this project and it's ecosystem better by implementing more example of Recharts, either translating them from the original docs (and filing issues for missing pieces) or creating your own advanced examples that could help out the community

**Comment by samme78** [comment]
I've implemented another one of the Pie charts examples. Mostly to get a feel for the github workflow and learn how to contribute to Open source projects.

Anyways, I'm missing the dominantbaseline prop in Feliz. Its used by the original recharts example (https://jsfiddle.net/alidingling/c9pL8k61/ line 13).

Do you have time to add it? Or could you point me to where and how I should add it?

**Comment by Zaid-Ajaj** [comment]
> I've implemented another one of the Pie charts examples. Mostly to get a feel for the github workflow and learn how to contribute to Open source projects.

Hello @samme78, that is great to hear, I would love to see it added to the docs! 

> Anyways, I'm missing the dominantbaseline prop in Feliz. Its used by the original recharts example (https://jsfiddle.net/alidingling/c9pL8k61/ line 13).

> Do you have time to add it? Or could you point me to where and how I should add it?

I have just added it to the standard properties and published a new version as of 0.65.2 to see how it is implemented, see [this comment](https://github.com/Zaid-Ajaj/Feliz/commit/e366a83e655a7e00e0c52f84c3a3795e99af1592) so next time you know where to look if you want to add it your self. 

If you have any questions or help with how the docs work, please let me know!
