### ISSUE TITLE
Error with Feliz 2.7

### ISSUE THREAD

**Issue by ciphertools** [Zaid-Ajaj/Feliz#586]
**Compiled with problems:
WARNING in ./src/Client/output/AdminTypes.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\...\src\Client\output\fable_modules\Feliz.2.6.0\Styles.fs'**

Since updating my SAFE Stack project with Feliz 2.7 (I love Feliz, so I was keen to try the latest version :-) ), I get this error when running the project.  Forcing Feliz back to 2.6.0 removes the error.

**Comment by Zaid-Ajaj** [comment]
Hi there @ciphertools source maps are usually generated at the user code as far as I know 🤔 maybe try clear out your Fable-generated JS files?

**Comment by ciphertools** [comment]
Thank you - that sorted it out.  Specifically, I renamed the output folder in the src/Client folder to a back-up name and Feliz 2.7 now runs fine.
