### ISSUE TITLE
Feliz.Markdown escapeHtml doesn't seem to work

### ISSUE THREAD

**Issue by LuisFX** [Zaid-Ajaj/Feliz#589]
I have the following code:

```xml
<a href="http://link.com/" target="_blank">Hello!</a>
```

```fsharp
Feliz.Markdown.Markdown.markdown [
  Markdown.markdown.escapeHtml false
  Markdown.markdown.skipHtml false
  Markdown.markdown.children props.Message
]                                  
```

My only intention, is to render links that open in a new tab/window using target blank.

The react-markdown seems to require a plugin, but I can't sort out how to get it working.

**Comment by Zaid-Ajaj** [comment]
I think you can override how a link is rendered and add the `target="_blank"` attribute to it
