### ISSUE TITLE
UseElmish: Failed to resolve import "use-sync-external-store/shim"

### ISSUE THREAD

**Issue by Larocceau** [Zaid-Ajaj/Feliz#590]
I'm trying to set up Feliz.UseElmish in my SAFE app, but there seems to be a problem with the NPM dependency "use-sync-external-store/shim".

After installing and implementing UseElmish, I get the error in Vite:
Failed to resolve import "use-sync-external-store/shim" from "output\fable_modules\Feliz.UseElmish.2.5.0\UseElmish.fs.js". Does the file exist?

**Comment by Larocceau** [comment]
Oh damn, I thought paket took care of that. Thanks!

**Comment by MangelMaxime** [comment]
Paket only takes care of NuGet dependencies. 

In general, any `import` errors you see coming from Node, `vite`, etc. are related to NPM packages
