### ISSUE TITLE
Expanding Feliz.Rechart

### ISSUE THREAD

**Issue by Freymaurer** [Zaid-Ajaj/Feliz#596]
Hello! I am currently using Feliz.Rechart and added some more properties (for example for sector) and would like to add an addtional chart to the examples.

Is this something you would like to have? Can you give me some CI commands i should run for testing or is there any documentation on how to contribute?

**Comment by MangelMaxime** [comment]
I think this repository is using NPM scripts.

If that's the case running `npm run start` should start a local server with the documentation.

**Comment by Freymaurer** [comment]
I'll open a PR as soon as i finished the example 🙂

**Comment by Freymaurer** [comment]
sadly i got no time for finishing the example, so will close for now
