### ISSUE TITLE
"Directory import use-sync-external-store\shim is not supported" in UseElmish.fs.js

### ISSUE THREAD

**Issue by reneederer** [Zaid-Ajaj/Feliz#598]
Hello,

I ran into an exception using mocha.

I created a project using dotnet template "feliz" and added a separate mocha test project.
Running ```mocha dist/fable/Quittiermaske/tests``` throws the exception:

![image](https://github.com/Zaid-Ajaj/Feliz/assets/12987718/f8f4aa9d-2271-4171-a41a-62ee5e7b28cd)

I suspect in fable_modules/Feliz.UseElmish.2.5.0/UseElmish.fs.js the line 
```import { useSyncExternalStore } from "use-sync-external-store/shim";```
should actually be
```import { useSyncExternalStore } from "use-sync-external-store/shim/index.js";```.
After I changed this line, mocha ran without errors.

**Comment by reneederer** [comment]
I found a workaround:
```mocha --loader=ts-node/esm dist/fable/Quittiermaske/tests```

**Comment by MangelMaxime** [comment]
Hello,

The problem is because Mocha does not support ESM out of the box.

Solutions:

1. Add a loader to mocha like you discovered
2. Change your tests framework to something like Vitest, Jest, Ava, etc.
3. Compile your code to CommonJS before executing Mocha
