### ISSUE TITLE
Use with Elmish documentation is lacking integration

### ISSUE THREAD

**Issue by pkese** [Zaid-Ajaj/Feliz#601]
I've been trying to understand the https://zaid-ajaj.github.io/Feliz/#/Feliz/UseWithElmish example.

Unfortunately there are a few lines missing ... the Elmish `Program.mkProgram` stuff down at the bottom.

- What libraries do I need to include
- which lines should I add to the end of that example
- will Elmish.React work with Feliz
- are there any particlularities with Hmr

It would be really nice if somebody added those few missing lines to that example to make if complete.

**Comment by MangelMaxime** [comment]
This section is trying to say that Feliz is compatible with any normal Elmish application which use React as the rendering layer.

You can use any Elmish application and add Feliz to it. Feliz is a replacement for Fable.React

> * will Elmish.React work with Feliz

Yes

> * are there any particlularities with Hmr

Like with any Elmish application you need to use [Fable.Elmish.HMR](https://elmish.github.io/hmr/) you don't need to follow any particular convention when using HMR with Elmish we are much more forgiving than hot-refresh from React.

**Comment by pkese** [comment]
Thanks @MangelMaxime 

I managed to figured it out myself in the meanwhile... it's just that it took me time and effort to do so.

So I added a pull request, to save time and help other people who might wish to achieve the same result
