### ISSUE TITLE
style.animationDelay and style.animationDuration incorrect milliseconds

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#61]
The following produce 234ms instead of the expected 1234ms:
```
style.animationDelay (System.TimeSpan.FromMilliseconds 1234.)
style.animationDuration (System.TimeSpan.FromMilliseconds 1234.)
```

**Comment by Zaid-Ajaj** [comment]
Hello @zanaptak, thanks a lot for filing the issue, should be fixed (along with #62) now and available as per v0.60.0. If the problem persists, please re-open the issue :smile:
