### ISSUE TITLE
Multiple elements child to root

### ISSUE THREAD

**Issue by reinux** [Zaid-Ajaj/Feliz#621]
Sorry I'm probably missing something obvious here, but is there a way to have multiple child elements to the root where the program is injected?

For example:

```fsharp
let view model dispatch =
  [  div [ Html.text "something" ]
    div [ Html.text "something else" ]
  ]
```

This naturally causes a type error, since it's expecting a `ReactElement` as opposed to a `ReactElement list`.

The reason I ask is that Bulma may or may not misbehave unless its elements are the direct child of `<body>`.

**Comment by Zaid-Ajaj** [comment]
Hi @reinux you can use `React.fragment [ ... ]` for this:
```fs
let view model dispatch = React.fragment [
  div [ Html.text "something" ]
  div [ Html.text "something else" ]
]
```

**Comment by reinux** [comment]
Ah, no wonder I couldn't find it. It's under `React`. Thanks!
