### ISSUE TITLE
Solidify Recharts API: Use specialized attribute types for specific elements

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#66]
Instead of 
```fs
Recharts.lineChart : IReactProperty list -> ReactElement
```
have
```
Recharts.lineChart : ILineChartProperty list -> ReactElement
```
Where `ILineChartProperty` is the specialized property type for the `Recharts.lineChart` element. 

functions within the `lineChart` type will return `ILineChartProperty` and so on and so forth for the rest of the types. 

Of course would be awesome if someone would like to give this a try with PR, let me know if you want to take it!

**Comment by Shmew** [comment]
This is how I do the [Feliz.Plotly](https://github.com/Shmew/Feliz.Plotly) attributes, so there's additional material to take from if needed.

**Comment by Zaid-Ajaj** [comment]
This has been fixed :) thanks @kaashyapan
