### ISSUE TITLE
styleList and classList naming

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#7]
The distinguishing feature of styleList and classList is not that they are lists, but that they are conditional.

I propose they be renamed `styleIf` and `classIf` or something similar.

Or, an alternative approach with helpers is maybe an option, to avoid having separate style and styleList/styleIf altogether. (Need a way to represent a false/null value in this scenario.) This is probably not much different from just using if-then-else but could be a bit easier to digest.

```
prop.style [
    style.display.flex |> ifCond model.isDisplayed
    style.display.none |> ifNotCond model.isDisplayed
]
```

**Comment by Zaid-Ajaj** [comment]
I can probably add an alias like `stylesWhen` for `styleList` but the for the second proposition, an if-else expression should suffice
