### ISSUE TITLE
Using props functions to lift up state can result in unexpected behaviour

### ISSUE THREAD

**Issue by bethmaloney** [Zaid-Ajaj/Feliz#70]
I ran into some behavior that I found confusing. I've recreated a simple example demonstrating the behaviour. counterControl takes a function that causes the parent component to update the state (increment the count).

```fsharp
module App

open Feliz
open Browser.Dom

let counterControl = React.functionComponent <| fun (props: {| incrementCount: unit -> unit; |}) ->
  Html.div [
    Html.button [
      prop.text "Increment"
      prop.onClick (fun _ -> props.incrementCount())
    ]
  ]

let counterView = React.functionComponent <| fun (props: {| count: int |}) ->
  Html.div [
    Html.h1 props.count
  ]

let view = React.functionComponent <| fun () ->
  let count, setCount = React.useState 0
  let incrementCount = fun () -> setCount (count + 1)

  Html.div [
    counterControl {| incrementCount = incrementCount |}
    counterView {| count = count |}
  ]


ReactDOM.render(view(), document.getElementById("elmish-app"))
```

Only the first click increments the counter. Subsequent clicks set the state to 1. Changing counterControl to use Fable.React.FunctionComponent.Of makes the component work as expected. I believe this is because [functionComponent](https://github.com/Zaid-Ajaj/Feliz/blob/021e647424af44500d53693994b8acf312b4cbf3/Feliz/React.fs#L38) uses Fable.React.Helpers.memoEqualsButFunctions which effectively "fixes" the count value in incrementCount.

I don't feel like this behavior is intuitive but I'm not sure what the best approach is.

1. We could change functionComponent to not memoize by default. This is the same behaviour as React. It would then be up to the developer to decide when to use memo
2. Change functionComponent to use memoization that also considers functions. This means that  if the props contains a function a re-render will occur every time. Once React.useCallback has been implemented then this can be used to prevent rerenders
3. Keep the behaviour but make a note in the documentation about this behaviour under Common Pitfalls.

I'm happy to make a PR as long as the fix isn't too complex.

**Comment by Zaid-Ajaj** [comment]
Hello @bethmaloney, thanks a lot for filing the issue with the detailed repro!

I agree that this behavior is confusing and unexpected just because the developer is using functions in the props and I very much like the first proposal: 

> We could change functionComponent to not memoize by default. This is the same behaviour as React. It would then be up to the developer to decide when to use memo 

I want to stay as close as possible to the React way such that the best practices from React can be seemingly used from here as well by looking up docs or issues. 

A PR would be awesome if you want to take a stab at it :)

**Comment by Zaid-Ajaj** [comment]
Should be fixed as of v0.65.0 🎉 can you take it for a spin to see if the problem is resolved? Please re-open the issue if the problem persists

**Comment by Zaid-Ajaj** [comment]
Tested with 0.65.0 and all work as expected

**Comment by bethmaloney** [comment]
Thank you for the quick response :)

I've updated to latest version and the problem's resolves 🎉

**Comment by OnurGumus** [comment]
@Zaid-Ajaj , I can see you have removed the overload, but what about if I want to memoize?

**Comment by Shmew** [comment]
You will want to use `React.useCallback` or `React.useCallbackRef` to memo a function when passing it as a prop.
