### ISSUE TITLE
Add missing documentation to style properties

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#75]
Similar to #44 but for style attributes that haven't been documented yet. Help is very much appreciated and PR's always welcome

**Comment by Shmew** [comment]
These should all be covered now [here](https://github.com/Zaid-Ajaj/Feliz/pull/80). There were a couple I didn't see on MDN web docs so I'll let you fill those in.

**Comment by Zaid-Ajaj** [comment]
This is resolved thanks to @Shmew
