### ISSUE TITLE
NuGet package fails to install

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#8]
NuGet package fails to install for me for any version. I don't think it's environmental, I can install other packages. Using Windows 10, .NET Core SDK 2.2.301.

```
dotnet add package Feliz --version 0.18.0
Writing C:\Users\zaphod\AppData\Local\Temp\tmpA1D6.tmp
info : Adding PackageReference for package 'Feliz' into project 'C:\src\HtmlCssDsl\HtmlCssDsl\HtmlCssDsl.fsproj'.
info : Restoring packages for C:\src\HtmlCssDsl\HtmlCssDsl\HtmlCssDsl.fsproj...
info : Package 'Feliz' is compatible with all the specified frameworks in project 'C:\src\HtmlCssDsl\HtmlCssDsl\HtmlCssDsl.fsproj'.
error: Value cannot be null.
error: Parameter name: path1
```

**Comment by Zaid-Ajaj** [comment]
Hmm the error message looks pretty clear to me:
```
info : Package 'Feliz' is compatible with all the specified frameworks in project 'C:\src\HtmlCssDsl\HtmlCssDsl\HtmlCssDsl.fsproj'.
```
I can install successfully from nuget without problems, can you please post your `.fsproj` here? Thanks!

**Comment by zanaptak** [comment]
I think that's a satisfied precondition, not an error.

The problem was ultimately a leftover project reference to Feliz.fsproj that was conflicting with the package. Sorry for the false alarm.
