### ISSUE TITLE
Recommend TypedCssClasses into the docs

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Feliz#83]
Rename page "Type-Safe CSS" into "Type-Safe Styles" and instead have a page "Type-Safe CSS" to explain and recommend the usage of [zanaptak/TypedCssClasses](https://github.com/zanaptak/TypedCssClasses) with Feliz applications. 

Also add the type provider into the Feliz template

**Comment by Zaid-Ajaj** [comment]
Published docs at [Feliz/Type-Safe CSS](https://zaid-ajaj.github.io/Feliz/#/Feliz/TypeSafeCss)

@zanaptak is this good enough? please let me know otherwise if I have missed something :smile:

**Comment by zanaptak** [comment]
Great, thanks for the reference, I think you explained the justification more clearly than I even did. 😃 

Cosmetically it seems the site is not handling the long code block -- on smaller browser width I am getting the text cut off on the right, with no horizontal scroll available.

**Comment by Zaid-Ajaj** [comment]
Yeah it is not *very* responsive on mid-size screens / tablets. I haven't spent much time on responsiveness of the docs because usually people look them on a laptop/computer screen. I will look into it soon
