### ISSUE TITLE
style.transform multiple values

### ISSUE THREAD

**Issue by zanaptak** [Zaid-Ajaj/Feliz#87]
[`transform`](https://developer.mozilla.org/en-US/docs/web/css/transform) can take multiple values so maybe it could work similar to `transitionProperty`:
```fs
style.transform [
  transform.scale ...
  transform.rotate ...
  ...
]
```

Also need to make sure there are float overloads where appropriate, e.g. `scale`.

**Comment by Zaid-Ajaj** [comment]
Should be easy to add, I will leave it up for grabs for now till someone picks it up or I do it this weekend :smile:
