### ISSUE TITLE
Add literals for Google Fonts

### ISSUE THREAD

**Issue by Shmew** [Zaid-Ajaj/Feliz#89]
Probably worth adding these as well, maybe a sub module so it's `fonts.google.someFont`.

Also the font-family property having an overload to accept a list would be good so they can specify backup fonts.

**Comment by Zaid-Ajaj** [comment]
Sounds like a good idea! This is up for grabs :smile: PRs are welcome

**Comment by Shmew** [comment]
Yeah I'll probably do it when I have the time, just posting it here so it's not forgotten or someone else wants to take it.

**Comment by Shmew** [comment]
Looking at this further it may not be something I do anytime soon, there are a *lot* of Google Fonts, and to implement this properly you'd probably want to generate not only the font family name, but backup font types and also generate Uri if they want it for requesting the API specifically. Luckily their API makes this task seem relatively easy.

**Comment by Zaid-Ajaj** [comment]
Now that I looked into the google fonts, this indeed sounds like work for a generator or better yet, a type provider. Maybe an external library is better suited for this instead of randomly adding font-names to this base library

**Comment by Shmew** [comment]
My thoughts exactly.
