### ISSUE TITLE
Trouble with Firefox and HMR in template

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz#97]
Testing the template. HMR works, but I get a lot of these all the time, at fairly regular intervals:

![image](https://user-images.githubusercontent.com/7766733/68074849-7a4d6d00-fda0-11e9-8899-c88e06fbb76b.png)

Can you reproduce? Does this indicate that something should be changed in the sample?

**Comment by Zaid-Ajaj** [comment]
I think this is a known issue in HMR where you have to install Redux dev tools browser extension to resolve it, preferably with Chrome, I don't know if the problem gets fixed in Firefox. See [troubleshooting/Diagnostics](https://safe-stack.github.io/docs/faq-troubleshooting/) from the SAFE docs where is it pretty much the same issue over there

**Comment by Zaid-Ajaj** [comment]
Note: Better to add this into the docs as wells

**Comment by Shmew** [comment]
You need to setup a proxy in your dev server settings like this:

in your `CONFIG`:

```
devServerProxy: {
        '/api': {
            target: 'http://localhost:' + (process.env.GIRAFFE_FABLE_PORT || '8085'),
            changeOrigin: true,
        },
        '/ws': {
            target: 'http://localhost:' + (process.env.GIRAFFE_FABLE_PORT || '8085'),
            changeOrigin: true,
            ws: true
        }
    },
```

and then in your `module.exports`:

```
devServer: {
        contentBase: CONFIG.assetsDir,
        hot: true,
        inline: true,
        port: CONFIG.devServerPort,
        proxy: CONFIG.devServerProxy,
        historyApiFallback: true
    },
```

**Comment by cmeeren** [comment]
@Shmew sorry, I don't know where `CONFIG` and `module.exports` is; could you give me more concrete pointers or where to add this? For the record, I just tried with the dotnet Feliz template.

**Comment by Shmew** [comment]
That would go in the [webpack.config.js](https://github.com/Zaid-Ajaj/Feliz/blob/master/Feliz.Template/Content/webpack.config.js).

**Comment by Zaid-Ajaj** [comment]
Confirmed that installing [Redux DevTools](https://addons.mozilla.org/en-CA/firefox/addon/reduxdevtools/) in Firefox solves this issue. @cmeeren Can you please confirm and close the issue if it is resolved?

**Comment by cmeeren** [comment]
Fixed, thanks!

**Comment by Shmew** [comment]
Oh, I thought you were actually trying to use websockets. It spits out the same error message when trying to do that and the dev server proxy isn't setup right. 😅
